import { useState, useMemo } from 'react'
import { Routes, Route } from 'react-router-dom'
import DashboardLayout from '../../shared/DashboardLayout'
import { useAuth } from '../../../contexts/AuthContext'
import { useCollection } from '../../../hooks/useCollection'
import StatCard from '../../shared/StatCard'
import DataTable from '../../shared/DataTable'
import Modal from '../../shared/Modal'
import ProfilePage from '../../shared/ProfilePage'
import PopiaModule from '../../shared/PopiaModule'
import SetupChecklist from '../../shared/SetupChecklist'
import { collection, addDoc, serverTimestamp, doc, deleteDoc, updateDoc, increment } from 'firebase/firestore'
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage'
import { db, storage } from '../../../services/firebase'
import {
  PlusCircle, Trash2, MapPin, Eye, Pencil, List, Zap, Landmark,
  Percent as PercentIcon, TrendingUp, Download, X, Loader2, Wrench,
  AlertTriangle, CheckCircle2, Clock,
} from 'lucide-react'
import CampaignsModule from '../../shared/CampaignsModule'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'

// ── Currency formatter ────────────────────────────────────────────────────────
const fmt = n => `R ${Number(n ?? 0).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

// ── PDF styles ────────────────────────────────────────────────────────────────
const ps = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 9, color: '#1a1a1a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  brand: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#5c9e8a' },
  sub: { fontSize: 9, color: '#666', marginTop: 2 },
  title: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 16 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, borderBottomWidth: 0.5, borderBottomColor: '#e5e7eb' },
  label: { color: '#555' },
  value: { fontFamily: 'Helvetica-Bold' },
  total: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, marginTop: 8, backgroundColor: '#f0f7f4', paddingHorizontal: 8, borderRadius: 4 },
  totalLabel: { fontFamily: 'Helvetica-Bold', fontSize: 10 },
  totalValue: { fontFamily: 'Helvetica-Bold', fontSize: 10, color: '#5c9e8a' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', fontSize: 8, color: '#999' },
})

function OwnerStatementPDF({ data }) {
  const { property, owner, month, rentCollected, commission, managementFee, expenses, netPayout, businessName, generatedAt } = data
  return (
    <Document>
      <Page size="A4" style={ps.page}>
        <View style={ps.header}>
          <View>
            <Text style={ps.brand}>{businessName || 'Tlhiso Property'}</Text>
            <Text style={ps.sub}>Owner Statement</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={ps.sub}>Period: {month}</Text>
            <Text style={ps.sub}>Generated: {generatedAt}</Text>
          </View>
        </View>

        <Text style={ps.title}>Statement for {property} — {owner}</Text>

        <View style={ps.row}><Text style={ps.label}>Rent Collected</Text><Text style={ps.value}>{fmt(rentCollected)}</Text></View>
        <View style={ps.row}><Text style={ps.label}>Commission ({commission}%)</Text><Text style={ps.value}>({fmt(rentCollected * commission / 100)})</Text></View>
        <View style={ps.row}><Text style={ps.label}>Management Fee</Text><Text style={ps.value}>({fmt(managementFee)})</Text></View>
        <View style={ps.row}><Text style={ps.label}>Expenses / Maintenance</Text><Text style={ps.value}>({fmt(expenses)})</Text></View>
        <View style={ps.total}>
          <Text style={ps.totalLabel}>Net Payout to Owner</Text>
          <Text style={ps.totalValue}>{fmt(netPayout)}</Text>
        </View>

        <View style={ps.footer}>
          <Text>Generated by Tlhiso — tlhiso.com</Text>
          <Text>Confidential</Text>
        </View>
      </Page>
    </Document>
  )
}

async function downloadStatementPDF(data) {
  const blob = await pdf(<OwnerStatementPDF data={data} />).toBlob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Statement_${data.property}_${data.month}.pdf`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Shared UI helpers ─────────────────────────────────────────────────────────
function Field({ label, error, textarea, select, children, ...props }) {
  const cls = 'w-full rounded-xl border border-border px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/30'
  return (
    <label className="block">
      <span className="mb-1.5 block text-xs font-semibold text-ink-secondary">{label}</span>
      {textarea ? <textarea {...props} className={cls + ' resize-none h-24'} /> :
       select ? <select {...props} className={cls}>{children}</select> :
       <input {...props} className={cls} />}
      {error && <p className="mt-1 text-xs text-red-500">{error}</p>}
    </label>
  )
}

function PageHead({ title, subtitle, action }) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-3">
      <div>
        <h2 className="text-lg font-bold text-ink">{title}</h2>
        {subtitle && <p className="mt-0.5 text-sm text-ink-secondary">{subtitle}</p>}
      </div>
      {action}
    </div>
  )
}

function AddButton({ onClick, children }) {
  return (
    <button onClick={onClick}
      className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#4e7d6d]">
      <PlusCircle size={15} /> {children}
    </button>
  )
}

function SectionCard({ icon: Icon, title, action, children }) {
  return (
    <div className="rounded-card border border-border bg-white shadow-card">
      <div className="flex items-center justify-between border-b border-border px-5 py-3.5">
        <div className="flex items-center gap-2">
          {Icon && <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary-light text-primary"><Icon size={14} /></span>}
          <h3 className="text-sm font-bold text-ink">{title}</h3>
        </div>
        {action}
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

function EmptyState({ icon: Icon, message }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
      {Icon && <span className="flex h-12 w-12 items-center justify-center rounded-full bg-surface-2 text-ink-secondary"><Icon size={20} /></span>}
      <p className="text-sm text-ink-secondary">{message}</p>
    </div>
  )
}

// ── Overview ──────────────────────────────────────────────────────────────────
function Overview() {
  const { user, profile } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const maintenance = useCollection(uid ? `users/${uid}/maintenance` : null)
  const rentRoll = useCollection(uid ? `users/${uid}/rentRoll` : null)

  const now = new Date()
  const thisMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const currentRR = rentRoll.filter(r => r.month === thisMonth)
  const paid = currentRR.filter(r => r.status === 'Paid').length
  const arrears = currentRR.filter(r => r.status === 'Arrears').length
  const activeTenants = tenants.filter(t => t.status === 'Active').length
  const openMaintenance = maintenance.filter(m => m.status === 'Open').length
  const totalRent = tenants.filter(t => t.status === 'Active').reduce((s, t) => s + Number(t.rentAmount ?? 0), 0)

  return (
    <div className="space-y-6">
      <SetupChecklist industry="property" />
      <PageHead
        title={`Welcome back${profile?.name ? `, ${profile.name.split(' ')[0]}` : ''}`}
        subtitle="Here's how your portfolio is performing."
      />
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Properties" value={properties.length} icon="🏘️" trend={`${tenants.length} tenants total`} trendTone="flat" />
        <StatCard label="Active Tenants" value={activeTenants} icon="👥" color="blue" trend={currentRR.length ? `${paid} paid · ${arrears} in arrears` : '—'} trendTone={arrears ? 'down' : 'up'} />
        <StatCard label="Monthly Rent Roll" value={fmt(totalRent)} icon="💰" color="purple" />
        <StatCard label="Open Maintenance" value={openMaintenance} icon="🔧" color="orange" trend={openMaintenance ? 'Needs attention' : 'All clear'} trendTone={openMaintenance ? 'down' : 'up'} />
      </div>

      <SectionCard icon={MapPin} title="Properties Overview"
        action={<a href="/property/properties" className="text-xs font-semibold text-primary hover:underline">View all →</a>}>
        {properties.length === 0
          ? <EmptyState icon={MapPin} message="No properties added yet." />
          : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {properties.map(p => (
                <div key={p.id} className="rounded-lg border border-border bg-surface-2 p-4 transition hover:border-primary/40 hover:shadow-card">
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-bold text-ink">{p.name}</p>
                    <span className="rounded-full bg-primary-light px-2 py-0.5 text-[10px] font-semibold text-primary">{p.type}</span>
                  </div>
                  <p className="mt-1 text-xs text-ink-secondary">{p.address}</p>
                  <p className="mt-2 text-xs font-medium text-ink">{p.units} units</p>
                </div>
              ))}
            </div>
        }
      </SectionCard>
    </div>
  )
}

// ── Properties ────────────────────────────────────────────────────────────────
function Properties() {
  const { user } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ name: '', address: '', type: 'Residential', units: '', purchasePrice: '', owner: '' })

  async function save() {
    if (!uid || !form.name) return
    await addDoc(collection(db, 'users', uid, 'properties'), { ...form, createdAt: serverTimestamp() })
    setOpen(false)
    setForm({ name: '', address: '', type: 'Residential', units: '', purchasePrice: '', owner: '' })
  }

  const cols = [
    { key: 'name', label: 'Property Name' },
    { key: 'address', label: 'Address' },
    { key: 'type', label: 'Type' },
    { key: 'units', label: 'Units' },
    { key: 'owner', label: 'Owner' },
    { key: 'actions', label: '', sortable: false, render: r => (
      <button onClick={e => { e.stopPropagation(); if (!window.confirm('Delete this property? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'properties', r.id)) }}
        className="rounded p-1 text-red-400 hover:bg-red-50"><Trash2 size={14} /></button>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Properties" subtitle="Your building & property register"
        action={<AddButton onClick={() => setOpen(true)}>Add Property</AddButton>} />
      <DataTable columns={cols} data={properties} emptyMessage="No properties yet." />
      <Modal open={open} onClose={() => setOpen(false)} title="New Property">
        <div className="space-y-4">
          <Field label="Property Name *" value={form.name} onChange={e => setForm(f=>({...f,name:e.target.value}))} />
          <Field label="Address" value={form.address} onChange={e => setForm(f=>({...f,address:e.target.value}))} />
          <Field label="Type" select value={form.type} onChange={e => setForm(f=>({...f,type:e.target.value}))}>
            {['Residential','Commercial','Industrial','Mixed Use'].map(t=><option key={t}>{t}</option>)}
          </Field>
          <Field label="Number of Units" type="number" value={form.units} onChange={e => setForm(f=>({...f,units:e.target.value}))} />
          <Field label="Purchase Price (R)" type="number" value={form.purchasePrice} onChange={e => setForm(f=>({...f,purchasePrice:e.target.value}))} />
          <Field label="Owner" value={form.owner} onChange={e => setForm(f=>({...f,owner:e.target.value}))} />
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Property</button>
        </div>
      </Modal>
    </div>
  )
}

// ── Tenants ───────────────────────────────────────────────────────────────────
function Tenants() {
  const { user } = useAuth()
  const uid = user?.uid
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const [open, setOpen] = useState(false)
  const [docFile, setDocFile] = useState(null)
  const [form, setForm] = useState({
    firstName: '', lastName: '', idNumber: '', phone: '', email: '',
    propertyId: '', unitNumber: '', leaseStart: '', leaseEnd: '',
    rentAmount: '', depositPaid: '', status: 'Active',
    escalationRate: '10', escalationMonth: '',
  })
  const [viewing, setViewing] = useState(null)
  const [editing, setEditing] = useState(null)
  const [editForm, setEditForm] = useState({
    firstName: '', lastName: '', idNumber: '', phone: '', email: '',
    propertyId: '', unitNumber: '', leaseStart: '', leaseEnd: '',
    rentAmount: '', depositPaid: '', status: 'Active',
    escalationRate: '10', escalationMonth: '',
  })

  async function save() {
    if (!uid || !form.firstName) return
    let docUrl = ''
    if (docFile) {
      const storageRef = ref(storage, `users/${uid}/tenants/${Date.now()}_${docFile.name}`)
      await uploadBytes(storageRef, docFile)
      docUrl = await getDownloadURL(storageRef)
    }
    const prop = properties.find(p => p.id === form.propertyId)
    await addDoc(collection(db, 'users', uid, 'tenants'), {
      ...form, property: prop?.name ?? '', documentUrl: docUrl, createdAt: serverTimestamp(),
    })
    setOpen(false)
    setForm({ firstName: '', lastName: '', idNumber: '', phone: '', email: '', propertyId: '', unitNumber: '', leaseStart: '', leaseEnd: '', rentAmount: '', depositPaid: '', status: 'Active', escalationRate: '10', escalationMonth: '' })
  }

  async function saveEdit() {
    if (!uid || !editForm.firstName || !editing) return
    const prop = properties.find(p => p.id === editForm.propertyId)
    await updateDoc(doc(db, 'users', uid, 'tenants', editing.id), {
      ...editForm, property: prop?.name ?? editing.property ?? '',
    })
    setEditing(null)
  }

  const statusColor = s => ({ Active: 'bg-green-100 text-green-700', 'Notice Given': 'bg-amber-100 text-amber-700', Vacated: 'bg-gray-100 text-gray-600' }[s] ?? '')

  const cols = [
    { key: 'firstName', label: 'First Name' },
    { key: 'lastName', label: 'Last Name' },
    { key: 'property', label: 'Property' },
    { key: 'unitNumber', label: 'Unit' },
    { key: 'rentAmount', label: 'Rent', render: r => fmt(r.rentAmount) },
    { key: 'status', label: 'Status', render: r => <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${statusColor(r.status)}`}>{r.status}</span> },
    { key: 'actions', label: '', sortable: false, render: r => (
      <div className="flex items-center gap-1">
        <button onClick={e => { e.stopPropagation(); setViewing(r) }}
          title="View" className="rounded p-1 text-ink-secondary hover:bg-surface-2"><Eye size={14} /></button>
        <button onClick={e => { e.stopPropagation(); setEditing(r); setEditForm({ firstName: r.firstName||'', lastName: r.lastName||'', idNumber: r.idNumber||'', phone: r.phone||'', email: r.email||'', propertyId: r.propertyId||'', unitNumber: r.unitNumber||'', leaseStart: r.leaseStart||'', leaseEnd: r.leaseEnd||'', rentAmount: r.rentAmount||'', depositPaid: r.depositPaid||'', status: r.status||'Active', escalationRate: r.escalationRate||'10', escalationMonth: r.escalationMonth||'' }) }}
          title="Edit" className="rounded p-1 text-primary hover:bg-primary-light"><Pencil size={14} /></button>
        <button onClick={e => { e.stopPropagation(); if (!window.confirm('Delete this tenant? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'tenants', r.id)) }}
          title="Delete" className="rounded p-1 text-red-400 hover:bg-red-50"><Trash2 size={14} /></button>
      </div>
    )},
  ]

  const tenantFormFields = (f, setF) => (
    <div className="grid grid-cols-2 gap-4">
      <Field label="First Name *" value={f.firstName} onChange={e => setF(x=>({...x,firstName:e.target.value}))} />
      <Field label="Last Name *" value={f.lastName} onChange={e => setF(x=>({...x,lastName:e.target.value}))} />
      <Field label="SA ID Number" value={f.idNumber} onChange={e => setF(x=>({...x,idNumber:e.target.value}))} />
      <Field label="Phone" value={f.phone} onChange={e => setF(x=>({...x,phone:e.target.value}))} />
      <Field label="Email" type="email" value={f.email} onChange={e => setF(x=>({...x,email:e.target.value}))} />
      <Field label="Property" select value={f.propertyId} onChange={e => setF(x=>({...x,propertyId:e.target.value}))}>
        <option value="">Select…</option>
        {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
      </Field>
      <Field label="Unit Number" value={f.unitNumber} onChange={e => setF(x=>({...x,unitNumber:e.target.value}))} />
      <Field label="Rent Amount (R)" type="number" value={f.rentAmount} onChange={e => setF(x=>({...x,rentAmount:e.target.value}))} />
      <Field label="Lease Start" type="date" value={f.leaseStart} onChange={e => setF(x=>({...x,leaseStart:e.target.value}))} />
      <Field label="Lease End" type="date" value={f.leaseEnd} onChange={e => setF(x=>({...x,leaseEnd:e.target.value}))} />
      <Field label="Deposit Paid (R)" type="number" value={f.depositPaid} onChange={e => setF(x=>({...x,depositPaid:e.target.value}))} />
      <Field label="Status" select value={f.status} onChange={e => setF(x=>({...x,status:e.target.value}))}>
        {['Active','Notice Given','Vacated'].map(s=><option key={s}>{s}</option>)}
      </Field>
      <Field label="Annual Escalation (%)" type="number" value={f.escalationRate} onChange={e => setF(x=>({...x,escalationRate:e.target.value}))} />
      <Field label="Escalation Month (1-12)" type="number" min="1" max="12" placeholder="e.g. 3 for March" value={f.escalationMonth} onChange={e => setF(x=>({...x,escalationMonth:e.target.value}))} />
    </div>
  )

  return (
    <div className="space-y-4">
      <PageHead title="Tenants" subtitle="Lease holders, escalation & documents"
        action={<AddButton onClick={() => setOpen(true)}>Add Tenant</AddButton>} />
      <DataTable columns={cols} data={tenants} emptyMessage="No tenants yet." />

      {/* Add modal */}
      <Modal open={open} onClose={() => setOpen(false)} title="New Tenant" size="lg">
        {tenantFormFields(form, setForm)}
        <div className="col-span-2 mt-3">
          <span className="mb-1.5 block text-xs font-semibold text-ink-secondary">Upload Document (Lease, ID, etc.)</span>
          <input type="file" onChange={e => setDocFile(e.target.files?.[0] ?? null)} className="text-sm text-ink-secondary" />
        </div>
        <button onClick={save} className="mt-4 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Tenant</button>
      </Modal>

      {/* View modal */}
      <Modal open={!!viewing} onClose={() => setViewing(null)} title="Tenant Details">
        {viewing && (
          <div className="space-y-3 text-sm">
            {[
              { label: 'Full Name', value: `${viewing.firstName||''} ${viewing.lastName||''}`.trim() },
              { label: 'SA ID Number', value: viewing.idNumber },
              { label: 'Phone', value: viewing.phone },
              { label: 'Email', value: viewing.email },
              { label: 'Property', value: viewing.property },
              { label: 'Unit Number', value: viewing.unitNumber },
              { label: 'Rent Amount', value: viewing.rentAmount ? fmt(viewing.rentAmount) : null },
              { label: 'Deposit Paid', value: viewing.depositPaid ? fmt(viewing.depositPaid) : null },
              { label: 'Lease Start', value: viewing.leaseStart },
              { label: 'Lease End', value: viewing.leaseEnd },
              { label: 'Status', value: viewing.status },
              { label: 'Escalation Rate', value: viewing.escalationRate ? `${viewing.escalationRate}% per annum` : null },
              { label: 'Escalation Month', value: viewing.escalationMonth ? `Month ${viewing.escalationMonth}` : null },
            ].map(({ label, value }) => value ? (
              <div key={label} className="flex flex-col gap-0.5 rounded-xl bg-surface-2 px-4 py-2.5">
                <span className="text-[11px] font-semibold uppercase tracking-wide text-ink-secondary">{label}</span>
                <span className="text-sm text-ink">{value}</span>
              </div>
            ) : null)}
            {viewing.documentUrl && (
              <a href={viewing.documentUrl} target="_blank" rel="noreferrer"
                className="inline-flex items-center gap-1.5 rounded-lg bg-primary-light px-3 py-2 text-xs font-semibold text-primary hover:bg-primary hover:text-white transition">
                View Uploaded Document →
              </a>
            )}
          </div>
        )}
      </Modal>

      {/* Edit modal */}
      <Modal open={!!editing} onClose={() => setEditing(null)} title="Edit Tenant" size="lg">
        {tenantFormFields(editForm, setEditForm)}
        <button onClick={saveEdit} className="mt-4 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Changes</button>
      </Modal>
    </div>
  )
}

// ── Rent Roll ─────────────────────────────────────────────────────────────────
function RentRoll() {
  const { user } = useAuth()
  const uid = user?.uid
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const rentRoll = useCollection(uid ? `users/${uid}/rentRoll` : null)

  const now = new Date()
  const defaultMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const [month, setMonth] = useState(defaultMonth)
  const [payingId, setPayingId] = useState(null)
  const [payModal, setPayModal] = useState(null)
  const [payDate, setPayDate] = useState(new Date().toISOString().slice(0, 10))
  const [applying, setApplying] = useState(false)

  // Entries for selected month
  const monthEntries = useMemo(() => rentRoll.filter(r => r.month === month), [rentRoll, month])

  // For tenants not yet in this month's roll, derive a row
  const rows = useMemo(() => {
    const activeTenants = tenants.filter(t => t.status === 'Active')
    return activeTenants.map(t => {
      const entry = monthEntries.find(e => e.tenantId === t.id)
      const rentAmt = Number(t.rentAmount ?? 0)
      // Arrears aging
      const today = new Date()
      const monthStart = new Date(month + '-01')
      const diffDays = Math.floor((today - monthStart) / 86400000)
      let aging = ''
      if (entry?.status !== 'Paid') {
        if (diffDays >= 90) aging = '90+ days'
        else if (diffDays >= 60) aging = '60 days'
        else if (diffDays >= 30) aging = '30 days'
        else if (diffDays > 0) aging = `${diffDays} days`
      }
      // Escalation detection
      const escMonth = Number(t.escalationMonth)
      const escRate = Number(t.escalationRate ?? 10)
      const currentMonth = now.getMonth() + 1
      const isEscalationMonth = escMonth && escMonth === currentMonth
      return {
        id: entry?.id,
        tenantId: t.id,
        name: `${t.firstName} ${t.lastName}`,
        property: t.property,
        unit: t.unitNumber,
        rentAmount: rentAmt,
        status: entry?.status ?? 'Pending',
        paidDate: entry?.paidDate ?? '',
        aging,
        isEscalationMonth,
        escRate,
        escalationRate: t.escalationRate,
      }
    })
  }, [tenants, monthEntries, month])

  const paid = rows.filter(r => r.status === 'Paid').length
  const arrears = rows.filter(r => r.status === 'Arrears').length
  const totalExpected = rows.reduce((s, r) => s + r.rentAmount, 0)
  const totalCollected = rows.filter(r => r.status === 'Paid').reduce((s, r) => s + r.rentAmount, 0)

  async function recordPayment(row) {
    if (!uid) return
    setPayingId(row.tenantId)
    if (row.id) {
      await updateDoc(doc(db, 'users', uid, 'rentRoll', row.id), { status: 'Paid', paidDate: payDate })
    } else {
      await addDoc(collection(db, 'users', uid, 'rentRoll'), {
        tenantId: row.tenantId, tenantName: row.name, property: row.property,
        unit: row.unit, rentAmount: row.rentAmount, month, status: 'Paid', paidDate: payDate,
        createdAt: serverTimestamp(),
      })
    }
    setPayingId(null)
    setPayModal(null)
  }

  async function markArrears(row) {
    if (!uid) return
    if (row.id) {
      await updateDoc(doc(db, 'users', uid, 'rentRoll', row.id), { status: 'Arrears' })
    } else {
      await addDoc(collection(db, 'users', uid, 'rentRoll'), {
        tenantId: row.tenantId, tenantName: row.name, property: row.property,
        unit: row.unit, rentAmount: row.rentAmount, month, status: 'Arrears',
        createdAt: serverTimestamp(),
      })
    }
  }

  async function applyEscalation(row) {
    if (!uid || !row.tenantId) return
    setApplying(row.tenantId)
    const newRent = Math.round(row.rentAmount * (1 + row.escRate / 100))
    await updateDoc(doc(db, 'users', uid, 'tenants', row.tenantId), { rentAmount: String(newRent) })
    setApplying(null)
  }

  const agingColor = a => {
    if (a.includes('90')) return 'text-red-600 font-bold'
    if (a.includes('60')) return 'text-orange-500 font-semibold'
    if (a.includes('30')) return 'text-amber-500'
    return 'text-ink-secondary'
  }

  const statusBadge = s => ({
    Paid: 'bg-green-100 text-green-700',
    Arrears: 'bg-red-100 text-red-600',
    Pending: 'bg-gray-100 text-gray-500',
  }[s] ?? 'bg-gray-100 text-gray-500')

  return (
    <div className="space-y-4">
      <PageHead title="Rent Roll" subtitle="Daily view — who's paid, who's late"
        action={
          <div className="flex items-center gap-2">
            <input type="month" value={month} onChange={e => setMonth(e.target.value)}
              className="rounded-xl border border-border px-3 py-2 text-sm outline-none focus:border-primary" />
          </div>
        }
      />

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Expected" value={fmt(totalExpected)} icon="📋" trendTone="flat" />
        <StatCard label="Collected" value={fmt(totalCollected)} icon="✅" color="blue" trendTone="up" />
        <StatCard label="Outstanding" value={fmt(totalExpected - totalCollected)} icon="⏳" color="orange" trendTone={totalCollected < totalExpected ? 'down' : 'up'} />
        <StatCard label="In Arrears" value={arrears} icon="🚨" color="orange" trend={`${paid} paid`} trendTone={arrears ? 'down' : 'up'} />
      </div>

      {/* Rent roll table */}
      <div className="overflow-hidden rounded-card border border-border bg-white shadow-card">
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-surface-2 text-xs font-semibold text-ink-secondary">
              <tr>
                {['Tenant', 'Property', 'Unit', 'Rent', 'Status', 'Arrears Age', 'Actions'].map(h => (
                  <th key={h} className="px-4 py-3 text-left">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {rows.length === 0 && (
                <tr><td colSpan={7} className="px-4 py-8 text-center text-ink-secondary text-sm">No active tenants for this month.</td></tr>
              )}
              {rows.map(row => (
                <tr key={row.tenantId} className="hover:bg-surface-2/50 transition">
                  <td className="px-4 py-3 font-medium text-ink">
                    {row.name}
                    {row.isEscalationMonth && (
                      <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700">
                        <TrendingUp size={10} /> Escalation Due
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-ink-secondary">{row.property}</td>
                  <td className="px-4 py-3 text-ink-secondary">{row.unit}</td>
                  <td className="px-4 py-3 font-semibold text-ink">{fmt(row.rentAmount)}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${statusBadge(row.status)}`}>{row.status}</span>
                  </td>
                  <td className={`px-4 py-3 text-xs ${row.aging ? agingColor(row.aging) : 'text-ink-secondary'}`}>
                    {row.aging || (row.status === 'Paid' ? '—' : 'Current')}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-1 flex-wrap">
                      {row.status !== 'Paid' && (
                        <>
                          <button onClick={() => { setPayModal(row); setPayDate(new Date().toISOString().slice(0,10)) }}
                            className="rounded px-2 py-1 text-xs font-semibold text-green-700 bg-green-50 hover:bg-green-100">
                            {payingId === row.tenantId ? <Loader2 size={12} className="animate-spin" /> : 'Mark Paid'}
                          </button>
                          <button onClick={() => markArrears(row)}
                            className="rounded px-2 py-1 text-xs font-semibold text-red-600 bg-red-50 hover:bg-red-100">
                            Arrears
                          </button>
                        </>
                      )}
                      {row.isEscalationMonth && row.status === 'Paid' && (
                        <button onClick={() => applyEscalation(row)}
                          className="rounded px-2 py-1 text-xs font-semibold text-amber-700 bg-amber-50 hover:bg-amber-100">
                          {applying === row.tenantId ? <Loader2 size={12} className="animate-spin" /> : `Apply ${row.escRate}% Escalation`}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pay modal */}
      <Modal open={!!payModal} onClose={() => setPayModal(null)} title="Record Payment">
        {payModal && (
          <div className="space-y-4">
            <p className="text-sm text-ink">Recording payment for <strong>{payModal.name}</strong> — {fmt(payModal.rentAmount)}</p>
            <Field label="Payment Date" type="date" value={payDate} onChange={e => setPayDate(e.target.value)} />
            <button onClick={() => recordPayment(payModal)} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Confirm Payment</button>
          </div>
        )}
      </Modal>
    </div>
  )
}

// ── Utilities ─────────────────────────────────────────────────────────────────
function Utilities() {
  const { user } = useAuth()
  const uid = user?.uid
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const bills = useCollection(uid ? `users/${uid}/utilityBills` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({
    tenantId: '', billingMonth: new Date().toISOString().slice(0, 7),
    electricity: '', electricityRate: '2.50', water: '', levy: '', other: '', description: '', status: 'Unpaid',
  })

  const electricityTotal = Number(form.electricity || 0) * Number(form.electricityRate || 0)
  const billTotal = electricityTotal + Number(form.water || 0) + Number(form.levy || 0) + Number(form.other || 0)

  async function save() {
    if (!uid || !form.tenantId) return
    const tenant = tenants.find(t => t.id === form.tenantId)
    await addDoc(collection(db, 'users', uid, 'utilityBills'), {
      ...form,
      tenantName: tenant ? `${tenant.firstName} ${tenant.lastName}` : '',
      property: tenant?.property ?? '',
      unit: tenant?.unitNumber ?? '',
      electricityTotal,
      total: billTotal,
      createdAt: serverTimestamp(),
    })
    setOpen(false)
    setForm({ tenantId: '', billingMonth: new Date().toISOString().slice(0, 7), electricity: '', electricityRate: '2.50', water: '', levy: '', other: '', description: '', status: 'Unpaid' })
  }

  const cols = [
    { key: 'tenantName', label: 'Tenant' },
    { key: 'property', label: 'Property' },
    { key: 'unit', label: 'Unit' },
    { key: 'billingMonth', label: 'Month' },
    { key: 'electricityTotal', label: 'Electricity', render: r => r.electricityTotal ? fmt(r.electricityTotal) : '—' },
    { key: 'water', label: 'Water', render: r => r.water ? fmt(r.water) : '—' },
    { key: 'levy', label: 'Levy', render: r => r.levy ? fmt(r.levy) : '—' },
    { key: 'total', label: 'Total', render: r => <span className="font-semibold">{fmt(r.total)}</span> },
    { key: 'status', label: 'Status', render: r => (
      <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${r.status === 'Paid' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>{r.status}</span>
    )},
    { key: 'actions', label: '', sortable: false, render: r => r.status !== 'Paid' && (
      <button onClick={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'utilityBills', r.id), { status: 'Paid' }) }}
        className="rounded px-2 py-1 text-xs font-semibold text-green-700 hover:bg-green-50">Mark Paid</button>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Utilities" subtitle="Electricity, water & levy recovery per unit"
        action={<AddButton onClick={() => setOpen(true)}>Add Bill</AddButton>} />
      <DataTable columns={cols} data={bills} emptyMessage="No utility bills yet." />

      <Modal open={open} onClose={() => setOpen(false)} title="New Utility Bill" size="lg">
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Field label="Tenant *" select value={form.tenantId} onChange={e => setForm(f=>({...f,tenantId:e.target.value}))}>
              <option value="">Select tenant…</option>
              {tenants.filter(t=>t.status==='Active').map(t=><option key={t.id} value={t.id}>{t.firstName} {t.lastName} — {t.property} {t.unitNumber}</option>)}
            </Field>
            <Field label="Billing Month" type="month" value={form.billingMonth} onChange={e => setForm(f=>({...f,billingMonth:e.target.value}))} />
            <Field label="Electricity (kWh)" type="number" value={form.electricity} onChange={e => setForm(f=>({...f,electricity:e.target.value}))} />
            <Field label="Rate per kWh (R)" type="number" value={form.electricityRate} onChange={e => setForm(f=>({...f,electricityRate:e.target.value}))} />
            <Field label="Water (R)" type="number" value={form.water} onChange={e => setForm(f=>({...f,water:e.target.value}))} />
            <Field label="Levy (R)" type="number" value={form.levy} onChange={e => setForm(f=>({...f,levy:e.target.value}))} />
            <Field label="Other (R)" type="number" value={form.other} onChange={e => setForm(f=>({...f,other:e.target.value}))} />
            <Field label="Status" select value={form.status} onChange={e => setForm(f=>({...f,status:e.target.value}))}>
              {['Unpaid','Paid'].map(s=><option key={s}>{s}</option>)}
            </Field>
          </div>
          <Field label="Notes" textarea value={form.description} onChange={e => setForm(f=>({...f,description:e.target.value}))} />
          <div className="rounded-xl bg-primary-light px-4 py-3">
            <p className="text-xs text-ink-secondary">Electricity total: {fmt(electricityTotal)}</p>
            <p className="mt-1 text-sm font-bold text-ink">Bill Total: {fmt(billTotal)}</p>
          </div>
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Bill</button>
        </div>
      </Modal>
    </div>
  )
}

// ── Trust Account ─────────────────────────────────────────────────────────────
function TrustAccount() {
  const { user } = useAuth()
  const uid = user?.uid
  const ledger = useCollection(uid ? `users/${uid}/trustLedger` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ date: new Date().toISOString().slice(0,10), type: 'Trust Receipt', description: '', amount: '', reference: '' })

  const sorted = useMemo(() => [...ledger].sort((a,b) => (a.date||'') < (b.date||'') ? -1 : 1), [ledger])

  // Running balances
  const withBalance = useMemo(() => {
    let trustBal = 0, bizBal = 0
    return sorted.map(e => {
      const amt = Number(e.amount ?? 0)
      if (e.type === 'Trust Receipt') trustBal += amt
      else if (e.type === 'Trust Disbursement') trustBal -= amt
      else if (e.type === 'Business Receipt') bizBal += amt
      else if (e.type === 'Business Disbursement') bizBal -= amt
      return { ...e, trustBalance: trustBal, bizBalance: bizBal }
    })
  }, [sorted])

  const trustBalance = withBalance.length ? withBalance[withBalance.length - 1].trustBalance : 0
  const bizBalance = withBalance.length ? withBalance[withBalance.length - 1].bizBalance : 0

  async function save() {
    if (!uid || !form.description || !form.amount) return
    await addDoc(collection(db, 'users', uid, 'trustLedger'), { ...form, createdAt: serverTimestamp() })
    setOpen(false)
    setForm({ date: new Date().toISOString().slice(0,10), type: 'Trust Receipt', description: '', amount: '', reference: '' })
  }

  const typeColor = t => ({
    'Trust Receipt': 'text-green-600', 'Trust Disbursement': 'text-red-500',
    'Business Receipt': 'text-blue-600', 'Business Disbursement': 'text-orange-500',
  }[t] ?? 'text-ink')

  const amtDisplay = e => {
    const amt = Number(e.amount ?? 0)
    const isDebit = e.type.includes('Disbursement')
    return <span className={isDebit ? 'text-red-500' : 'text-green-600'}>{isDebit ? `(${fmt(amt)})` : fmt(amt)}</span>
  }

  return (
    <div className="space-y-4">
      <PageHead title="Trust Account" subtitle="Separate client funds (trust) from agency income (business)"
        action={<AddButton onClick={() => setOpen(true)}>Add Entry</AddButton>} />

      <div className="grid grid-cols-2 gap-4">
        <div className="rounded-card border border-border bg-white shadow-card p-5">
          <p className="text-xs font-semibold text-ink-secondary mb-1">TRUST BALANCE (Client Funds)</p>
          <p className={`text-2xl font-bold ${trustBalance < 0 ? 'text-red-500' : 'text-green-600'}`}>{fmt(trustBalance)}</p>
          <p className="text-xs text-ink-secondary mt-1">PPRA regulated — client money only</p>
        </div>
        <div className="rounded-card border border-border bg-white shadow-card p-5">
          <p className="text-xs font-semibold text-ink-secondary mb-1">BUSINESS BALANCE (Agency Income)</p>
          <p className={`text-2xl font-bold ${bizBalance < 0 ? 'text-red-500' : 'text-primary'}`}>{fmt(bizBalance)}</p>
          <p className="text-xs text-ink-secondary mt-1">Commissions, fees, agency revenue</p>
        </div>
      </div>

      <div className="overflow-hidden rounded-card border border-border bg-white shadow-card">
        <div className="border-b border-border px-5 py-3.5 flex items-center gap-2">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary-light text-primary"><Landmark size={14} /></span>
          <h3 className="text-sm font-bold text-ink">Ledger</h3>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-surface-2 text-xs font-semibold text-ink-secondary">
              <tr>{['Date','Type','Description','Reference','Amount','Trust Bal','Biz Bal'].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr>
            </thead>
            <tbody className="divide-y divide-border">
              {withBalance.length === 0 && <tr><td colSpan={7} className="px-4 py-8 text-center text-ink-secondary">No entries yet.</td></tr>}
              {withBalance.map(e => (
                <tr key={e.id} className="hover:bg-surface-2/50">
                  <td className="px-4 py-3 text-ink-secondary">{e.date}</td>
                  <td className={`px-4 py-3 text-xs font-semibold ${typeColor(e.type)}`}>{e.type}</td>
                  <td className="px-4 py-3 text-ink">{e.description}</td>
                  <td className="px-4 py-3 text-ink-secondary">{e.reference}</td>
                  <td className="px-4 py-3">{amtDisplay(e)}</td>
                  <td className="px-4 py-3 font-semibold text-ink">{fmt(e.trustBalance)}</td>
                  <td className="px-4 py-3 font-semibold text-ink">{fmt(e.bizBalance)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <Modal open={open} onClose={() => setOpen(false)} title="New Ledger Entry">
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Field label="Date" type="date" value={form.date} onChange={e => setForm(f=>({...f,date:e.target.value}))} />
            <Field label="Type" select value={form.type} onChange={e => setForm(f=>({...f,type:e.target.value}))}>
              {['Trust Receipt','Trust Disbursement','Business Receipt','Business Disbursement'].map(t=><option key={t}>{t}</option>)}
            </Field>
            <Field label="Amount (R) *" type="number" value={form.amount} onChange={e => setForm(f=>({...f,amount:e.target.value}))} />
            <Field label="Reference" value={form.reference} onChange={e => setForm(f=>({...f,reference:e.target.value}))} />
          </div>
          <Field label="Description *" value={form.description} onChange={e => setForm(f=>({...f,description:e.target.value}))} />
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Entry</button>
        </div>
      </Modal>
    </div>
  )
}

// ── Owner Statements ───────────────────────────────────────────────────────────
function OwnerStatements() {
  const { user, profile } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const statements = useCollection(uid ? `users/${uid}/ownerStatements` : null)
  const [form, setForm] = useState({
    propertyId: '', owner: '', month: new Date().toISOString().slice(0,7),
    rentCollected: '', commission: '8', managementFee: '', expenses: '',
  })
  const [generating, setGenerating] = useState(false)

  const rentCollected = Number(form.rentCollected || 0)
  const commission = Number(form.commission || 0)
  const managementFee = Number(form.managementFee || 0)
  const expenses = Number(form.expenses || 0)
  const commissionAmt = rentCollected * commission / 100
  const netPayout = rentCollected - commissionAmt - managementFee - expenses

  async function generate() {
    if (!uid || !form.propertyId || !form.rentCollected) return
    setGenerating(true)
    const property = properties.find(p => p.id === form.propertyId)
    const data = {
      property: property?.name ?? form.propertyId,
      owner: form.owner || property?.owner || 'Owner',
      month: form.month,
      rentCollected, commission, managementFee, expenses, netPayout,
      businessName: profile?.businessName || profile?.name || 'Tlhiso Property',
      generatedAt: new Date().toLocaleDateString('en-ZA'),
    }
    await addDoc(collection(db, 'users', uid, 'ownerStatements'), { ...data, createdAt: serverTimestamp() })
    await downloadStatementPDF(data)
    setGenerating(false)
  }

  const cols = [
    { key: 'property', label: 'Property' },
    { key: 'owner', label: 'Owner' },
    { key: 'month', label: 'Month' },
    { key: 'rentCollected', label: 'Rent', render: r => fmt(r.rentCollected) },
    { key: 'netPayout', label: 'Net Payout', render: r => <span className="font-semibold text-primary">{fmt(r.netPayout)}</span> },
    { key: 'actions', label: '', sortable: false, render: r => (
      <button onClick={e => { e.stopPropagation(); downloadStatementPDF({ ...r, businessName: profile?.businessName || profile?.name || 'Tlhiso Property', generatedAt: new Date().toLocaleDateString('en-ZA') }) }}
        className="flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold text-primary hover:bg-primary-light">
        <Download size={12} /> PDF
      </button>
    )},
  ]

  return (
    <div className="space-y-6">
      <PageHead title="Owner Statements" subtitle="Generate rent statements & payout summaries for property owners" />

      <div className="rounded-card border border-border bg-white shadow-card p-5">
        <h3 className="text-sm font-bold text-ink mb-4">Generate New Statement</h3>
        <div className="grid grid-cols-2 gap-4">
          <Field label="Property *" select value={form.propertyId} onChange={e => setForm(f=>({...f,propertyId:e.target.value}))}>
            <option value="">Select property…</option>
            {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
          </Field>
          <Field label="Owner Name" value={form.owner} onChange={e => setForm(f=>({...f,owner:e.target.value}))} placeholder="Auto-filled from property" />
          <Field label="Statement Month" type="month" value={form.month} onChange={e => setForm(f=>({...f,month:e.target.value}))} />
          <Field label="Rent Collected (R) *" type="number" value={form.rentCollected} onChange={e => setForm(f=>({...f,rentCollected:e.target.value}))} />
          <Field label="Commission (%)" type="number" value={form.commission} onChange={e => setForm(f=>({...f,commission:e.target.value}))} />
          <Field label="Management Fee (R)" type="number" value={form.managementFee} onChange={e => setForm(f=>({...f,managementFee:e.target.value}))} />
          <div className="col-span-2">
            <Field label="Expenses / Maintenance (R)" type="number" value={form.expenses} onChange={e => setForm(f=>({...f,expenses:e.target.value}))} />
          </div>
        </div>

        {form.rentCollected && (
          <div className="mt-4 rounded-xl bg-surface-2 p-4 space-y-2 text-sm">
            <div className="flex justify-between"><span className="text-ink-secondary">Rent Collected</span><span className="font-semibold">{fmt(rentCollected)}</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Commission ({commission}%)</span><span className="text-red-500">({fmt(commissionAmt)})</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Management Fee</span><span className="text-red-500">({fmt(managementFee)})</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Expenses</span><span className="text-red-500">({fmt(expenses)})</span></div>
            <div className="flex justify-between border-t border-border pt-2"><span className="font-bold text-ink">Net Payout to Owner</span><span className="font-bold text-primary text-base">{fmt(netPayout)}</span></div>
          </div>
        )}

        <button onClick={generate} disabled={generating || !form.propertyId || !form.rentCollected}
          className="mt-4 flex items-center gap-2 rounded-xl bg-primary px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">
          {generating ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
          Generate & Download PDF
        </button>
      </div>

      <div>
        <h3 className="text-sm font-bold text-ink mb-3">Statement History</h3>
        <DataTable columns={cols} data={statements} emptyMessage="No statements generated yet." />
      </div>
    </div>
  )
}

// ── Commission ────────────────────────────────────────────────────────────────
function Commission() {
  const { user } = useAuth()
  const uid = user?.uid
  const commissions = useCollection(uid ? `users/${uid}/commissions` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({
    type: 'Letting', property: '', transactionValue: '', commissionRate: '8',
    description: '', date: new Date().toISOString().slice(0,10), status: 'Pending',
  })

  const commissionAmt = Number(form.transactionValue || 0) * Number(form.commissionRate || 0) / 100

  async function save() {
    if (!uid || !form.property) return
    await addDoc(collection(db, 'users', uid, 'commissions'), {
      ...form, commissionAmount: commissionAmt, createdAt: serverTimestamp(),
    })
    setOpen(false)
    setForm({ type: 'Letting', property: '', transactionValue: '', commissionRate: '8', description: '', date: new Date().toISOString().slice(0,10), status: 'Pending' })
  }

  const statusColor = s => ({ Pending: 'bg-amber-100 text-amber-700', Invoiced: 'bg-blue-100 text-blue-600', Paid: 'bg-green-100 text-green-700' }[s] ?? '')

  const cols = [
    { key: 'date', label: 'Date' },
    { key: 'type', label: 'Type' },
    { key: 'property', label: 'Property' },
    { key: 'transactionValue', label: 'Transaction Value', render: r => fmt(r.transactionValue) },
    { key: 'commissionRate', label: 'Rate', render: r => `${r.commissionRate}%` },
    { key: 'commissionAmount', label: 'Commission', render: r => <span className="font-semibold text-primary">{fmt(r.commissionAmount)}</span> },
    { key: 'status', label: 'Status', render: r => <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${statusColor(r.status)}`}>{r.status}</span> },
    { key: 'actions', label: '', sortable: false, render: r => (
      <div className="flex gap-1">
        {r.status === 'Pending' && (
          <button onClick={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'commissions', r.id), { status: 'Invoiced' }) }}
            className="rounded px-2 py-1 text-xs font-semibold text-blue-600 hover:bg-blue-50">Invoice</button>
        )}
        {r.status === 'Invoiced' && (
          <button onClick={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'commissions', r.id), { status: 'Paid' }) }}
            className="rounded px-2 py-1 text-xs font-semibold text-green-700 hover:bg-green-50">Mark Paid</button>
        )}
      </div>
    )},
  ]

  const totalPending = commissions.filter(c=>c.status==='Pending').reduce((s,c)=>s+Number(c.commissionAmount??0),0)
  const totalPaid = commissions.filter(c=>c.status==='Paid').reduce((s,c)=>s+Number(c.commissionAmount??0),0)

  return (
    <div className="space-y-4">
      <PageHead title="Commission Tracking" subtitle="Sales & lettings commissions"
        action={<AddButton onClick={() => setOpen(true)}>Add Commission</AddButton>} />

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">
        <StatCard label="Pending" value={fmt(totalPending)} icon="⏳" color="orange" />
        <StatCard label="Paid" value={fmt(totalPaid)} icon="✅" color="blue" />
        <StatCard label="Total Commissions" value={commissions.length} icon="📊" />
      </div>

      <DataTable columns={cols} data={commissions} emptyMessage="No commissions recorded yet." />

      <Modal open={open} onClose={() => setOpen(false)} title="New Commission">
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Field label="Type" select value={form.type} onChange={e => setForm(f=>({...f,type:e.target.value}))}>
              {['Letting','Sale','Management','Other'].map(t=><option key={t}>{t}</option>)}
            </Field>
            <Field label="Date" type="date" value={form.date} onChange={e => setForm(f=>({...f,date:e.target.value}))} />
            <Field label="Property *" value={form.property} onChange={e => setForm(f=>({...f,property:e.target.value}))} />
            <Field label="Transaction Value (R)" type="number" value={form.transactionValue} onChange={e => setForm(f=>({...f,transactionValue:e.target.value}))} />
            <Field label="Commission Rate (%)" type="number" value={form.commissionRate} onChange={e => setForm(f=>({...f,commissionRate:e.target.value}))} />
            <Field label="Status" select value={form.status} onChange={e => setForm(f=>({...f,status:e.target.value}))}>
              {['Pending','Invoiced','Paid'].map(s=><option key={s}>{s}</option>)}
            </Field>
          </div>
          <Field label="Description / Notes" textarea value={form.description} onChange={e => setForm(f=>({...f,description:e.target.value}))} />
          {form.transactionValue && (
            <div className="rounded-xl bg-primary-light px-4 py-3">
              <p className="text-sm font-bold text-ink">Commission Amount: {fmt(commissionAmt)}</p>
            </div>
          )}
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Commission</button>
        </div>
      </Modal>
    </div>
  )
}

// ── Maintenance ───────────────────────────────────────────────────────────────
function Maintenance() {
  const { user } = useAuth()
  const uid = user?.uid
  const logs = useCollection(uid ? `users/${uid}/maintenance` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ property: '', unit: '', description: '', priority: 'Medium', contractor: '', status: 'Open' })

  async function save() {
    if (!uid) return
    await addDoc(collection(db, 'users', uid, 'maintenance'), { ...form, createdAt: serverTimestamp() })
    setOpen(false)
    setForm({ property: '', unit: '', description: '', priority: 'Medium', contractor: '', status: 'Open' })
  }

  const priorityColor = p => ({ High: 'bg-red-100 text-red-700', Medium: 'bg-amber-100 text-amber-700', Low: 'bg-green-100 text-green-700' }[p] ?? '')

  const cols = [
    { key: 'property', label: 'Property' },
    { key: 'unit', label: 'Unit' },
    { key: 'description', label: 'Description' },
    { key: 'priority', label: 'Priority', render: r => <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${priorityColor(r.priority)}`}>{r.priority}</span> },
    { key: 'contractor', label: 'Contractor' },
    { key: 'status', label: 'Status' },
    { key: 'actions', label: '', sortable: false, render: r => (
      <button onClick={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'maintenance', r.id), { status: 'Resolved' }) }}
        className="rounded px-2 py-1 text-xs font-semibold text-green-700 hover:bg-green-50">Resolve</button>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Maintenance" subtitle="Track repairs & contractor jobs"
        action={<AddButton onClick={() => setOpen(true)}>Log Request</AddButton>} />
      <DataTable columns={cols} data={logs} emptyMessage="No maintenance requests." />
      <Modal open={open} onClose={() => setOpen(false)} title="New Maintenance Request">
        <div className="space-y-4">
          <Field label="Property" value={form.property} onChange={e => setForm(f=>({...f,property:e.target.value}))} />
          <Field label="Unit" value={form.unit} onChange={e => setForm(f=>({...f,unit:e.target.value}))} />
          <Field label="Description" textarea value={form.description} onChange={e => setForm(f=>({...f,description:e.target.value}))} />
          <Field label="Priority" select value={form.priority} onChange={e => setForm(f=>({...f,priority:e.target.value}))}>
            {['High','Medium','Low'].map(p=><option key={p}>{p}</option>)}
          </Field>
          <Field label="Assigned Contractor" value={form.contractor} onChange={e => setForm(f=>({...f,contractor:e.target.value}))} />
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Request</button>
        </div>
      </Modal>
    </div>
  )
}

function SimplePage({ title }) {
  return <div><h2 className="text-base font-bold text-ink mb-3">{title}</h2><p className="text-sm text-ink-secondary">This section is being built.</p></div>
}

export default function PropertyDashboard() {
  return (
    <DashboardLayout industry="property" pageTitle="Property Management">
      <Routes>
        <Route path="dashboard" element={<Overview />} />
        <Route path="properties" element={<Properties />} />
        <Route path="tenants" element={<Tenants />} />
        <Route path="rent-roll" element={<RentRoll />} />
        <Route path="utilities" element={<Utilities />} />
        <Route path="trust-account" element={<TrustAccount />} />
        <Route path="statements" element={<OwnerStatements />} />
        <Route path="commission" element={<Commission />} />
        <Route path="maintenance" element={<Maintenance />} />
        <Route path="campaigns" element={<CampaignsModule industry="property" />} />
        <Route path="profile" element={<ProfilePage industry="property" />} />
        <Route path="popia" element={<PopiaModule />} />
        <Route path="*" element={<SimplePage title="Coming Soon" />} />
      </Routes>
    </DashboardLayout>
  )
}
