import { useState, useMemo } from 'react'
import { Routes, Route, Link } from 'react-router-dom'
import DashboardLayout from '../../shared/DashboardLayout'
import { useAuth } from '../../../contexts/AuthContext'
import { useCollection } from '../../../hooks/useCollection'
import StatCard from '../../shared/StatCard'
import DataTable from '../../shared/DataTable'
import Modal from '../../shared/Modal'
import ProfilePage from '../../shared/ProfilePage'
import SetupChecklist from '../../shared/SetupChecklist'
import { collection, addDoc, serverTimestamp, doc, deleteDoc, updateDoc, increment } from 'firebase/firestore'
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage'
import { db, storage, functions } from '../../../services/firebase'
import { httpsCallable } from 'firebase/functions'
import {
  PlusCircle, Trash2, MapPin, Eye, Pencil, List, TrendingUp, Download, X, Loader2, Wrench,
  AlertTriangle, CheckCircle2, Clock, Bell, Users as UsersIcon, FileText, Upload,
  MessageSquare, Calendar as CalendarIcon, Phone as PhoneIcon,
} from 'lucide-react'
import CampaignsModule from '../../shared/CampaignsModule'
import SettingsPage from '../../shared/SettingsPage'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'

// ── Currency formatter ────────────────────────────────────────────────────────
const fmt = n => `R ${Number(n ?? 0).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

// ── PDF styles ────────────────────────────────────────────────────────────────
const ps = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 9, color: '#1a1a1a' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 },
  brand: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#5c9e8a' },
  sub: { fontSize: 9, color: '#666', marginTop: 2 },
  title: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 16 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 5, borderBottomWidth: 0.5, borderBottomColor: '#e5e7eb' },
  label: { color: '#555' },
  value: { fontFamily: 'Helvetica-Bold' },
  total: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, marginTop: 8, backgroundColor: '#f0f7f4', paddingHorizontal: 8, borderRadius: 4 },
  totalLabel: { fontFamily: 'Helvetica-Bold', fontSize: 10 },
  totalValue: { fontFamily: 'Helvetica-Bold', fontSize: 10, color: '#5c9e8a' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between', fontSize: 8, color: '#999' },
})

function OwnerStatementPDF({ data }) {
  const { property, owner, month, rentCollected, commission, managementFee, expenses, netPayout, businessName, generatedAt } = data
  return (
    <Document>
      <Page size="A4" style={ps.page}>
        <View style={ps.header}>
          <View>
            <Text style={ps.brand}>{businessName || 'Tlhiso Property'}</Text>
            <Text style={ps.sub}>Owner Statement</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={ps.sub}>Period: {month}</Text>
            <Text style={ps.sub}>Generated: {generatedAt}</Text>
          </View>
        </View>

        <Text style={ps.title}>Statement for {property} — {owner}</Text>

        <View style={ps.row}><Text style={ps.label}>Rent Collected</Text><Text style={ps.value}>{fmt(rentCollected)}</Text></View>
        <View style={ps.row}><Text style={ps.label}>Commission ({commission}%)</Text><Text style={ps.value}>({fmt(rentCollected * commission / 100)})</Text></View>
        <View style={ps.row}><Text style={ps.label}>Management Fee</Text><Text style={ps.value}>({fmt(managementFee)})</Text></View>
        <View style={ps.row}><Text style={ps.label}>Expenses / Maintenance</Text><Text style={ps.value}>({fmt(expenses)})</Text></View>
        <View style={ps.total}>
          <Text style={ps.totalLabel}>Net Payout to Owner</Text>
          <Text style={ps.totalValue}>{fmt(netPayout)}</Text>
        </View>

        <View style={ps.footer}>
          <Text>Generated by Tlhiso — tlhiso.com</Text>
          <Text>Confidential</Text>
        </View>
      </Page>
    </Document>
  )
}

async function downloadStatementPDF(data) {
  const blob = await pdf(<OwnerStatementPDF data={data} />).toBlob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Statement_${data.property}_${data.month}.pdf`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Shared UI helpers ─────────────────────────────────────────────────────────
function Field({ label, error, textarea, select, children, ...props }) {
  const cls = 'w-full rounded-xl border border-border px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/30'
  return (
    <label className="block">
      <span className="mb-1.5 block text-xs font-semibold text-ink-secondary">{label}</span>
      {textarea ? <textarea {...props} className={cls + ' resize-none h-24'} /> :
       select ? <select {...props} className={cls}>{children}</select> :
       <input {...props} className={cls} />}
      {error && <p className="mt-1 text-xs text-red-500">{error}</p>}
    </label>
  )
}

function PageHead({ title, subtitle, action }) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-3">
      <div>
        <h2 className="text-lg font-bold text-ink">{title}</h2>
        {subtitle && <p className="mt-0.5 text-sm text-ink-secondary">{subtitle}</p>}
      </div>
      {action}
    </div>
  )
}

function AddButton({ onClick, children }) {
  return (
    <button onClick={onClick}
      className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#4e7d6d]">
      <PlusCircle size={15} /> {children}
    </button>
  )
}

function SectionCard({ icon: Icon, title, action, children }) {
  return (
    <div className="rounded-card border border-border bg-white shadow-card">
      <div className="flex items-center justify-between border-b border-border px-5 py-3.5">
        <div className="flex items-center gap-2">
          {Icon && <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary-light text-primary"><Icon size={14} /></span>}
          <h3 className="text-sm font-bold text-ink">{title}</h3>
        </div>
        {action}
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

function EmptyState({ icon: Icon, message }) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 py-8 text-center">
      {Icon && <span className="flex h-12 w-12 items-center justify-center rounded-full bg-surface-2 text-ink-secondary"><Icon size={20} /></span>}
      <p className="text-sm text-ink-secondary">{message}</p>
    </div>
  )
}

// ── Overview ──────────────────────────────────────────────────────────────────
function Overview() {
  const { user, profile } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const maintenance = useCollection(uid ? `users/${uid}/maintenance` : null)
  const rentRoll = useCollection(uid ? `users/${uid}/rentRoll` : null)

  const now = new Date()
  const thisMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const currentRR = rentRoll.filter(r => r.month === thisMonth)
  const paid = currentRR.filter(r => r.status === 'Paid').length
  const arrears = currentRR.filter(r => r.status === 'Arrears').length
  const activeTenants = tenants.filter(t => t.status === 'Active').length
  const openMaintenance = maintenance.filter(m => m.status === 'Open').length
  const totalRent = tenants.filter(t => t.status === 'Active').reduce((s, t) => s + Number(t.rentAmount ?? 0), 0)

  return (
    <div className="space-y-6">
      <SetupChecklist industry="property" />
      <PageHead
        title={`Welcome back${profile?.name ? `, ${profile.name.split(' ')[0]}` : ''}`}
        subtitle="Here's how your portfolio is performing."
      />
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Properties" value={properties.length} icon="🏘️" trend={`${tenants.length} tenants total`} trendTone="flat" />
        <StatCard label="Active Tenants" value={activeTenants} icon="👥" color="blue" trend={currentRR.length ? `${paid} paid · ${arrears} in arrears` : '—'} trendTone={arrears ? 'down' : 'up'} />
        <StatCard label="Monthly Rent Roll" value={fmt(totalRent)} icon="💰" color="purple" />
        <StatCard label="Open Maintenance" value={openMaintenance} icon="🔧" color="orange" trend={openMaintenance ? 'Needs attention' : 'All clear'} trendTone={openMaintenance ? 'down' : 'up'} />
      </div>

      <SectionCard icon={MapPin} title="Properties Overview"
        action={<Link to="/property/properties" className="text-xs font-semibold text-primary hover:underline">View all →</Link>}>
        {properties.length === 0
          ? <EmptyState icon={MapPin} message="No properties added yet." />
          : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {properties.map(p => (
                <div key={p.id} className="rounded-lg border border-border bg-surface-2 p-4 transition hover:border-primary/40 hover:shadow-card">
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-bold text-ink">{p.name}</p>
                    <span className="rounded-full bg-primary-light px-2 py-0.5 text-[10px] font-semibold text-primary">{p.type}</span>
                  </div>
                  <p className="mt-1 text-xs text-ink-secondary">{p.address}</p>
                  <p className="mt-2 text-xs font-medium text-ink">{p.units} units</p>
                </div>
              ))}
            </div>
        }
      </SectionCard>
    </div>
  )
}

// ── Properties ────────────────────────────────────────────────────────────────
const PROP_BLANK = {
  name: '', reference: '', type: 'Residential', status: 'Active', description: '',
  // Location
  address: '', suburb: '', city: '', province: 'Gauteng', postalCode: '',
  // Physical
  units: '', erfNumber: '', erfSize: '', floorArea: '', yearBuilt: '', sectionalTitleNo: '',
  // Financial
  purchasePrice: '', marketValue: '', monthlyRates: '', levy: '', municipalAccount: '',
  // Ownership
  owner: '', ownershipType: 'Individual', titleDeedNo: '',
}

const SA_PROVINCES = [
  'Gauteng','Western Cape','KwaZulu-Natal','Eastern Cape',
  'Limpopo','Mpumalanga','North West','Free State','Northern Cape',
]

const PROP_STATUS_COLORS = {
  Active:           'bg-green-100 text-green-700',
  Vacant:           'bg-amber-100 text-amber-700',
  'Under Renovation': 'bg-blue-100 text-blue-600',
  'For Sale':       'bg-purple-100 text-purple-700',
}

function PropFormFields({ f, setF }) {
  const set = k => e => setF(x => ({ ...x, [k]: e.target.value }))
  return (
    <div className="space-y-5">
      {/* Property details */}
      <div>
        <p className="mb-3 text-xs font-bold uppercase tracking-wider text-primary">Property Details</p>
        <div className="grid grid-cols-2 gap-3">
          <div className="col-span-2"><Field label="Property Name *" value={f.name} onChange={set('name')} placeholder="e.g. Sunridge Estate Block A" /></div>
          <Field label="Reference / Code" value={f.reference} onChange={set('reference')} placeholder="e.g. PRO-001" />
          <Field label="Type" select value={f.type} onChange={set('type')}>
            {['Residential','Commercial','Industrial','Mixed Use','Student Accommodation','Short-Term Rental'].map(t=><option key={t}>{t}</option>)}
          </Field>
          <Field label="Status" select value={f.status} onChange={set('status')}>
            {Object.keys(PROP_STATUS_COLORS).map(s=><option key={s}>{s}</option>)}
          </Field>
          <Field label="Number of Units" type="number" value={f.units} onChange={set('units')} />
          <div className="col-span-2"><Field label="Description" textarea value={f.description} onChange={set('description')} /></div>
        </div>
      </div>
      {/* Location */}
      <div>
        <p className="mb-3 text-xs font-bold uppercase tracking-wider text-primary">Location</p>
        <div className="grid grid-cols-2 gap-3">
          <div className="col-span-2"><Field label="Street Address *" value={f.address} onChange={set('address')} placeholder="e.g. 12 Main Street" /></div>
          <Field label="Suburb" value={f.suburb} onChange={set('suburb')} />
          <Field label="City" value={f.city} onChange={set('city')} />
          <Field label="Province" select value={f.province} onChange={set('province')}>
            {SA_PROVINCES.map(p=><option key={p}>{p}</option>)}
          </Field>
          <Field label="Postal Code" value={f.postalCode} onChange={set('postalCode')} maxLength={4} />
        </div>
      </div>
      {/* Physical */}
      <div>
        <p className="mb-3 text-xs font-bold uppercase tracking-wider text-primary">Physical Details</p>
        <div className="grid grid-cols-2 gap-3">
          <Field label="ERF / Stand Number" value={f.erfNumber} onChange={set('erfNumber')} />
          <Field label="ERF Size (m²)" type="number" value={f.erfSize} onChange={set('erfSize')} />
          <Field label="Floor Area (m²)" type="number" value={f.floorArea} onChange={set('floorArea')} />
          <Field label="Year Built" type="number" value={f.yearBuilt} onChange={set('yearBuilt')} placeholder="e.g. 1998" />
          <div className="col-span-2"><Field label="Sectional Title Scheme No." value={f.sectionalTitleNo} onChange={set('sectionalTitleNo')} placeholder="If applicable" /></div>
        </div>
      </div>
      {/* Financial */}
      <div>
        <p className="mb-3 text-xs font-bold uppercase tracking-wider text-primary">Financial</p>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Purchase Price (R)" type="number" value={f.purchasePrice} onChange={set('purchasePrice')} />
          <Field label="Current Market Value (R)" type="number" value={f.marketValue} onChange={set('marketValue')} />
          <Field label="Monthly Rates & Taxes (R)" type="number" value={f.monthlyRates} onChange={set('monthlyRates')} />
          <Field label="Monthly Levy (R)" type="number" value={f.levy} onChange={set('levy')} />
          <div className="col-span-2"><Field label="Municipal Account No." value={f.municipalAccount} onChange={set('municipalAccount')} /></div>
        </div>
      </div>
      {/* Ownership */}
      <div>
        <p className="mb-3 text-xs font-bold uppercase tracking-wider text-primary">Ownership</p>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Owner Name" value={f.owner} onChange={set('owner')} />
          <Field label="Ownership Type" select value={f.ownershipType} onChange={set('ownershipType')}>
            {['Individual','Company','Trust','Close Corporation','Other'].map(o=><option key={o}>{o}</option>)}
          </Field>
          <div className="col-span-2"><Field label="Title Deed No." value={f.titleDeedNo} onChange={set('titleDeedNo')} /></div>
        </div>
      </div>
    </div>
  )
}

function Properties() {
  const { user } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const [open, setOpen] = useState(false)
  const [viewing, setViewing] = useState(null)
  const [editing, setEditing] = useState(null)
  const [form, setForm] = useState(PROP_BLANK)
  const [editForm, setEditForm] = useState(PROP_BLANK)
  const [saving, setSaving] = useState(false)

  async function save() {
    if (!uid || !form.name) { alert('Property name is required.'); return }
    setSaving(true)
    try {
      await addDoc(collection(db, 'users', uid, 'properties'), { ...form, createdAt: serverTimestamp() })
      setOpen(false); setForm(PROP_BLANK)
    } finally { setSaving(false) }
  }

  async function saveEdit() {
    if (!uid || !editForm.name || !editing) return
    setSaving(true)
    try {
      await updateDoc(doc(db, 'users', uid, 'properties', editing.id), editForm)
      setEditing(null)
    } finally { setSaving(false) }
  }

  function openEdit(p) {
    setEditing(p)
    setEditForm({ ...PROP_BLANK, ...p })
  }

  const activeTenants = p => tenants.filter(t => t.propertyId === p.id && t.status === 'Active').length
  const totalUnits = properties.reduce((s, p) => s + Number(p.units || 0), 0)
  const totalActive = properties.filter(p => p.status === 'Active').length

  return (
    <div className="space-y-5">
      <PageHead title="Properties" subtitle="Your building & property register"
        action={<AddButton onClick={() => setOpen(true)}>Add Property</AddButton>} />

      {/* Summary stats */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Total Properties" value={properties.length} icon="🏘️" />
        <StatCard label="Total Units" value={totalUnits} icon="🔑" color="blue" />
        <StatCard label="Active" value={totalActive} icon="✅" color="purple" />
        <StatCard label="Vacant / Other" value={properties.length - totalActive} icon="⏳" color="orange" trendTone={properties.length - totalActive > 0 ? 'down' : 'up'} />
      </div>

      {/* Property cards */}
      {properties.length === 0 ? (
        <EmptyState icon={MapPin} message="No properties yet. Click 'Add Property' to get started." />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
          {properties.map(p => {
            const occupied = activeTenants(p)
            const units = Number(p.units || 0)
            const occupancyPct = units > 0 ? Math.round((occupied / units) * 100) : 0
            return (
              <div key={p.id} className="group flex flex-col overflow-hidden rounded-2xl border border-border bg-white shadow-sm transition hover:shadow-md">
                {/* Card header */}
                <div className="flex items-start justify-between gap-2 border-b border-border bg-gradient-to-br from-primary-light/60 to-surface-2 px-5 py-4">
                  <div className="min-w-0">
                    <p className="truncate font-bold text-ink">{p.name}</p>
                    {p.reference && <p className="text-xs text-ink-secondary">{p.reference}</p>}
                  </div>
                  <span className={`flex-shrink-0 rounded-full px-2.5 py-0.5 text-[11px] font-semibold ${PROP_STATUS_COLORS[p.status] ?? 'bg-gray-100 text-gray-600'}`}>
                    {p.status || 'Active'}
                  </span>
                </div>

                {/* Card body */}
                <div className="flex flex-1 flex-col gap-3 p-5">
                  {/* Address */}
                  <div className="flex items-start gap-2 text-sm text-ink-secondary">
                    <MapPin size={13} className="mt-0.5 flex-shrink-0 text-primary" />
                    <span>{[p.address, p.suburb, p.city].filter(Boolean).join(', ') || '—'}</span>
                  </div>

                  {/* Key info grid */}
                  <div className="grid grid-cols-2 gap-2">
                    {[
                      { label: 'Type', value: p.type },
                      { label: 'Units', value: p.units || '—' },
                      { label: 'Owner', value: p.owner || '—' },
                      { label: 'ERF', value: p.erfNumber || '—' },
                    ].map(({ label, value }) => (
                      <div key={label} className="rounded-lg bg-surface-2 px-3 py-2">
                        <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-secondary">{label}</p>
                        <p className="mt-0.5 text-xs font-semibold text-ink truncate">{value}</p>
                      </div>
                    ))}
                  </div>

                  {/* Market value */}
                  {p.marketValue && (
                    <div className="rounded-lg border border-primary/20 bg-primary-light/30 px-3 py-2">
                      <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-secondary">Market Value</p>
                      <p className="text-sm font-bold text-primary">{fmt(p.marketValue)}</p>
                    </div>
                  )}

                  {/* Occupancy bar */}
                  {units > 0 && (
                    <div>
                      <div className="mb-1 flex justify-between text-[11px]">
                        <span className="font-semibold text-ink-secondary">Occupancy</span>
                        <span className="font-semibold text-ink">{occupied}/{units} units</span>
                      </div>
                      <div className="h-1.5 overflow-hidden rounded-full bg-surface-2">
                        <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${occupancyPct}%` }} />
                      </div>
                    </div>
                  )}
                </div>

                {/* Card actions */}
                <div className="flex items-center gap-1 border-t border-border px-4 py-2.5">
                  <button onClick={() => setViewing(p)} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold text-ink hover:bg-surface-2 transition">
                    <Eye size={12} /> View
                  </button>
                  <button onClick={() => openEdit(p)} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold text-primary hover:bg-primary-light transition">
                    <Pencil size={12} /> Edit
                  </button>
                  <button onClick={() => { if (!window.confirm('Delete this property? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'properties', p.id)) }}
                    className="rounded-lg p-1.5 text-red-400 hover:bg-red-50 transition">
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* Add modal */}
      <Modal open={open} onClose={() => setOpen(false)} title="New Property" size="xl">
        <PropFormFields f={form} setF={setForm} />
        <button onClick={save} disabled={saving} className="mt-5 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">
          {saving ? 'Saving…' : 'Save Property'}
        </button>
      </Modal>

      {/* Edit modal */}
      <Modal open={!!editing} onClose={() => setEditing(null)} title="Edit Property" size="xl">
        <PropFormFields f={editForm} setF={setEditForm} />
        <button onClick={saveEdit} disabled={saving} className="mt-5 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">
          {saving ? 'Saving…' : 'Save Changes'}
        </button>
      </Modal>

      {/* View modal */}
      <Modal open={!!viewing} onClose={() => setViewing(null)} title="Property Details" size="lg">
        {viewing && (
          <div className="space-y-5 text-sm">
            {/* Header */}
            <div className="flex items-start justify-between gap-3 rounded-xl bg-primary-light/40 px-4 py-4">
              <div>
                <p className="text-base font-bold text-ink">{viewing.name}</p>
                {viewing.reference && <p className="text-xs text-ink-secondary mt-0.5">Ref: {viewing.reference}</p>}
                <p className="mt-1 text-xs text-ink-secondary">{[viewing.address, viewing.suburb, viewing.city, viewing.province].filter(Boolean).join(', ')}</p>
              </div>
              <span className={`flex-shrink-0 rounded-full px-2.5 py-0.5 text-[11px] font-semibold ${PROP_STATUS_COLORS[viewing.status] ?? 'bg-gray-100 text-gray-600'}`}>{viewing.status}</span>
            </div>

            {[
              { title: 'Property Details', fields: [
                { label: 'Type', value: viewing.type },
                { label: 'Units', value: viewing.units },
                { label: 'Floor Area', value: viewing.floorArea ? `${viewing.floorArea} m²` : null },
                { label: 'ERF Size', value: viewing.erfSize ? `${viewing.erfSize} m²` : null },
                { label: 'ERF Number', value: viewing.erfNumber },
                { label: 'Year Built', value: viewing.yearBuilt },
                { label: 'Sectional Title No.', value: viewing.sectionalTitleNo },
              ]},
              { title: 'Financial', fields: [
                { label: 'Purchase Price', value: viewing.purchasePrice ? fmt(viewing.purchasePrice) : null },
                { label: 'Market Value', value: viewing.marketValue ? fmt(viewing.marketValue) : null },
                { label: 'Monthly Rates', value: viewing.monthlyRates ? fmt(viewing.monthlyRates) : null },
                { label: 'Monthly Levy', value: viewing.levy ? fmt(viewing.levy) : null },
                { label: 'Municipal Account', value: viewing.municipalAccount },
              ]},
              { title: 'Ownership', fields: [
                { label: 'Owner', value: viewing.owner },
                { label: 'Ownership Type', value: viewing.ownershipType },
                { label: 'Title Deed No.', value: viewing.titleDeedNo },
              ]},
            ].map(section => {
              const visible = section.fields.filter(f => f.value)
              if (!visible.length) return null
              return (
                <div key={section.title}>
                  <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-primary">{section.title}</p>
                  <div className="grid grid-cols-2 gap-2">
                    {visible.map(({ label, value }) => (
                      <div key={label} className="rounded-xl bg-surface-2 px-4 py-2.5">
                        <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-secondary">{label}</p>
                        <p className="mt-0.5 text-sm font-medium text-ink">{value}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )
            })}

            {viewing.description && (
              <div>
                <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-primary">Description</p>
                <p className="rounded-xl bg-surface-2 px-4 py-3 text-sm text-ink leading-relaxed">{viewing.description}</p>
              </div>
            )}

            <button onClick={() => { setViewing(null); openEdit(viewing) }}
              className="w-full rounded-xl border border-primary px-4 py-2.5 text-sm font-semibold text-primary hover:bg-primary-light transition">
              Edit this property
            </button>
          </div>
        )}
      </Modal>
    </div>
  )
}

// ── Tenant PDF ────────────────────────────────────────────────────────────────
function TenantProfilePDF({ t, businessName, generatedAt }) {
  const fullName = `${t.firstName || ''} ${t.lastName || ''}`.trim()
  const rows = (label, value) => value ? (
    <View style={ps.row} key={label}>
      <Text style={ps.label}>{label}</Text>
      <Text style={ps.value}>{value}</Text>
    </View>
  ) : null

  return (
    <Document>
      <Page size="A4" style={ps.page}>
        <View style={ps.header}>
          <View>
            <Text style={ps.brand}>{businessName || 'Tlhiso Property'}</Text>
            <Text style={ps.sub}>Tenant Profile</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={ps.sub}>Generated: {generatedAt}</Text>
            <Text style={ps.sub}>Status: {t.status || 'Active'}</Text>
          </View>
        </View>

        <Text style={ps.title}>{fullName}</Text>

        <Text style={{ ...ps.sub, marginBottom: 6, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', color: '#5c9e8a' }}>Personal Details</Text>
        {rows('Full Name', fullName)}
        {rows('SA ID Number', t.idNumber)}
        {rows('Phone', t.phone)}
        {rows('Email', t.email)}
        {rows('Current Address', t.currentAddress)}
        {rows('Employment Status', t.employmentStatus)}
        {rows('Employer', t.employer)}
        {rows('Employer Phone', t.employerPhone)}

        <Text style={{ ...ps.sub, marginTop: 14, marginBottom: 6, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', color: '#5c9e8a' }}>Lease Details</Text>
        {rows('Property', t.property)}
        {rows('Unit Number', t.unitNumber)}
        {rows('Lease Type', t.leaseType)}
        {rows('Lease Start', t.leaseStart)}
        {rows('Lease End', t.leaseEnd)}
        {rows('Occupants', t.occupants)}
        {rows('Parking Bay', t.parkingBay)}
        {rows('Pets Allowed', t.petsAllowed)}

        <Text style={{ ...ps.sub, marginTop: 14, marginBottom: 6, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', color: '#5c9e8a' }}>Financial</Text>
        {rows('Monthly Rent', t.rentAmount ? `R ${Number(t.rentAmount).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}` : null)}
        {rows('Deposit Paid', t.depositPaid ? `R ${Number(t.depositPaid).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}` : null)}
        {rows('Payment Method', t.paymentMethod)}
        {rows('Escalation Rate', t.escalationRate ? `${t.escalationRate}% per annum` : null)}
        {rows('Escalation Month', t.escalationMonth ? `Month ${t.escalationMonth}` : null)}

        {(t.emergencyName || t.emergencyPhone) && (
          <>
            <Text style={{ ...ps.sub, marginTop: 14, marginBottom: 6, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', color: '#5c9e8a' }}>Emergency Contact</Text>
            {rows('Name', t.emergencyName)}
            {rows('Relationship', t.emergencyRelation)}
            {rows('Phone', t.emergencyPhone)}
          </>
        )}

        {t.notes && (
          <>
            <Text style={{ ...ps.sub, marginTop: 14, marginBottom: 6, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', color: '#5c9e8a' }}>Notes</Text>
            <Text style={{ fontSize: 9, color: '#333', lineHeight: 1.5 }}>{t.notes}</Text>
          </>
        )}

        <View style={ps.footer}>
          <Text>{businessName || 'Tlhiso Property'} · Confidential tenant record</Text>
          <Text>Generated via Tlhiso</Text>
        </View>
      </Page>
    </Document>
  )
}

async function downloadTenantPDF(t, businessName) {
  const blob = await pdf(<TenantProfilePDF t={t} businessName={businessName} generatedAt={new Date().toLocaleDateString('en-ZA')} />).toBlob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Tenant_${t.firstName}_${t.lastName}_Profile.pdf`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Tenants ───────────────────────────────────────────────────────────────────
const TENANT_BLANK = {
  firstName: '', lastName: '', idNumber: '', phone: '', email: '', currentAddress: '',
  employmentStatus: 'Employed', employer: '', employerPhone: '',
  emergencyName: '', emergencyRelation: '', emergencyPhone: '',
  propertyId: '', unitNumber: '', leaseType: 'Fixed Term', leaseStart: '', leaseEnd: '',
  rentAmount: '', depositPaid: '', paymentMethod: 'EFT',
  escalationRate: '10', escalationMonth: '',
  occupants: '1', parkingBay: '', petsAllowed: 'No',
  status: 'Active', notes: '',
}

const STATUS_COLORS = {
  Active: 'bg-green-100 text-green-700',
  'Notice Given': 'bg-amber-100 text-amber-700',
  Vacated: 'bg-gray-100 text-gray-500',
}

function leaseInfo(t) {
  if (!t.leaseEnd) return null
  const today = new Date()
  const end = new Date(t.leaseEnd)
  const days = Math.floor((end - today) / 86400000)
  if (days < 0) return { label: 'Expired', color: 'bg-red-100 text-red-600', urgent: true }
  if (days <= 30) return { label: `${days}d left`, color: 'bg-red-100 text-red-600', urgent: true }
  if (days <= 60) return { label: `${days}d left`, color: 'bg-amber-100 text-amber-600', urgent: false }
  return { label: `${days}d left`, color: 'bg-green-100 text-green-700', urgent: false }
}

function TenantFormFields({ f, setF, properties, docFile, setDocFile }) {
  const set = k => e => setF(x => ({ ...x, [k]: e.target.value }))
  const SecHead = ({ label }) => (
    <div className="col-span-2 mt-2 flex items-center gap-3">
      <span className="text-[11px] font-bold uppercase tracking-wider text-primary">{label}</span>
      <span className="h-px flex-1 bg-border" />
    </div>
  )
  return (
    <div className="grid grid-cols-2 gap-4">
      <SecHead label="Personal Details" />
      <Field label="First Name *" value={f.firstName} onChange={set('firstName')} />
      <Field label="Last Name *" value={f.lastName} onChange={set('lastName')} />
      <Field label="SA ID Number (13 digits)" value={f.idNumber} onChange={set('idNumber')} maxLength={13} />
      <Field label="Phone (+27…)" value={f.phone} onChange={set('phone')} />
      <Field label="Email" type="email" value={f.email} onChange={set('email')} />
      <Field label="Employment Status" select value={f.employmentStatus} onChange={set('employmentStatus')}>
        {['Employed','Self-Employed','Unemployed','Student','Retired','Other'].map(s=><option key={s}>{s}</option>)}
      </Field>
      <Field label="Employer / Company" value={f.employer} onChange={set('employer')} />
      <Field label="Employer Phone" value={f.employerPhone} onChange={set('employerPhone')} />
      <div className="col-span-2"><Field label="Current / Previous Address" textarea value={f.currentAddress} onChange={set('currentAddress')} /></div>

      <SecHead label="Emergency Contact" />
      <Field label="Contact Name" value={f.emergencyName} onChange={set('emergencyName')} />
      <Field label="Relationship" value={f.emergencyRelation} onChange={set('emergencyRelation')} placeholder="e.g. Spouse, Parent" />
      <div className="col-span-2"><Field label="Contact Phone" value={f.emergencyPhone} onChange={set('emergencyPhone')} /></div>

      <SecHead label="Lease Details" />
      <Field label="Property *" select value={f.propertyId} onChange={set('propertyId')}>
        <option value="">Select property…</option>
        {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
      </Field>
      <Field label="Unit Number" value={f.unitNumber} onChange={set('unitNumber')} />
      <Field label="Lease Type" select value={f.leaseType} onChange={set('leaseType')}>
        {['Fixed Term','Month-to-Month','Periodic','Short-Term'].map(t=><option key={t}>{t}</option>)}
      </Field>
      <Field label="Status" select value={f.status} onChange={set('status')}>
        {['Active','Notice Given','Vacated'].map(s=><option key={s}>{s}</option>)}
      </Field>
      <Field label="Lease Start" type="date" value={f.leaseStart} onChange={set('leaseStart')} />
      <Field label="Lease End" type="date" value={f.leaseEnd} onChange={set('leaseEnd')} />
      <Field label="Number of Occupants" type="number" min="1" value={f.occupants} onChange={set('occupants')} />
      <Field label="Parking Bay" value={f.parkingBay} onChange={set('parkingBay')} placeholder="e.g. Bay 12 or N/A" />
      <Field label="Pets Allowed" select value={f.petsAllowed} onChange={set('petsAllowed')}>
        {['No','Yes — small pets','Yes — all pets'].map(p=><option key={p}>{p}</option>)}
      </Field>

      <SecHead label="Financial" />
      <Field label="Monthly Rent (R) *" type="number" value={f.rentAmount} onChange={set('rentAmount')} />
      <Field label="Deposit Paid (R)" type="number" value={f.depositPaid} onChange={set('depositPaid')} />
      <Field label="Payment Method" select value={f.paymentMethod} onChange={set('paymentMethod')}>
        {['EFT','Cash','Debit Order','Stop Order'].map(m=><option key={m}>{m}</option>)}
      </Field>
      <Field label="Annual Escalation (%)" type="number" value={f.escalationRate} onChange={set('escalationRate')} />
      <Field label="Escalation Month (1–12)" type="number" min="1" max="12" value={f.escalationMonth} onChange={set('escalationMonth')} placeholder="e.g. 3 for March" />

      <SecHead label="Documents & Notes" />
      <div className="col-span-2">
        <span className="mb-1.5 block text-xs font-semibold text-ink-secondary">Upload Document (Lease agreement, ID copy, etc.)</span>
        <input type="file" onChange={e => setDocFile(e.target.files?.[0] ?? null)} className="text-sm text-ink-secondary" />
      </div>
      <div className="col-span-2"><Field label="Notes / Remarks" textarea value={f.notes} onChange={set('notes')} /></div>
    </div>
  )
}

function Tenants() {
  const { user, profile } = useAuth()
  const uid = user?.uid
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const properties = useCollection(uid ? `users/${uid}/properties` : null)

  const [open,    setOpen]    = useState(false)
  const [viewing, setViewing] = useState(null)
  const [editing, setEditing] = useState(null)
  const [form,    setForm]    = useState(TENANT_BLANK)
  const [editForm,setEditForm]= useState(TENANT_BLANK)
  const [docFile, setDocFile] = useState(null)
  const [saving,  setSaving]  = useState(false)
  const [sending, setSending] = useState(null)
  const [pdfing,  setPdfing]  = useState(false)

  async function save() {
    if (!uid || !form.firstName || !form.lastName) { alert('First and last name are required.'); return }
    setSaving(true)
    try {
      let docUrl = ''
      if (docFile) {
        const storageRef = ref(storage, `users/${uid}/tenants/${Date.now()}_${docFile.name}`)
        await uploadBytes(storageRef, docFile)
        docUrl = await getDownloadURL(storageRef)
      }
      const prop = properties.find(p => p.id === form.propertyId)
      await addDoc(collection(db, 'users', uid, 'tenants'), {
        ...form, property: prop?.name ?? '', documentUrl: docUrl, createdAt: serverTimestamp(),
      })
      setOpen(false); setForm(TENANT_BLANK); setDocFile(null)
    } finally { setSaving(false) }
  }

  async function saveEdit() {
    if (!uid || !editForm.firstName || !editing) return
    setSaving(true)
    try {
      const prop = properties.find(p => p.id === editForm.propertyId)
      await updateDoc(doc(db, 'users', uid, 'tenants', editing.id), {
        ...editForm, property: prop?.name ?? editing.property ?? '',
      })
      setEditing(null)
    } finally { setSaving(false) }
  }

  function openEdit(t) {
    setEditing(t)
    setEditForm({ ...TENANT_BLANK, ...t })
  }

  async function sendSMS(t) {
    if (!t.phone) { alert('No phone number on file.'); return }
    setSending(t.id)
    try {
      const fn = httpsCallable(functions, 'sendSMS')
      const msg = `Hi ${t.firstName}, this is a message from your property manager. Please contact us if you have any queries.`
      await fn({ to: t.phone, message: msg })
      await addDoc(collection(db, 'users', uid, 'messages'), {
        to: t.phone, type: 'sms', body: msg, module: 'tenant-direct', status: 'sent', sentAt: serverTimestamp(),
      })
    } catch { alert('SMS failed — check BulkSMS credentials.') } finally { setSending(null) }
  }

  async function handleDownloadPDF(t) {
    setPdfing(t.id)
    try {
      await downloadTenantPDF(t, profile?.businessName || profile?.name || 'Tlhiso Property')
    } catch { alert('PDF generation failed.') } finally { setPdfing(null) }
  }

  // Stats
  const active     = tenants.filter(t => t.status === 'Active').length
  const onNotice   = tenants.filter(t => t.status === 'Notice Given').length
  const vacated    = tenants.filter(t => t.status === 'Vacated').length
  const totalRent  = tenants.filter(t => t.status === 'Active').reduce((s, t) => s + Number(t.rentAmount || 0), 0)
  const expiringSoon = tenants.filter(t => { const info = leaseInfo(t); return info?.urgent }).length

  const cols = [
    { key: 'firstName', label: 'Tenant', render: r => (
      <div>
        <p className="font-semibold text-ink">{r.firstName} {r.lastName}</p>
        <p className="text-xs text-ink-secondary">{r.idNumber || '—'}</p>
      </div>
    )},
    { key: 'property', label: 'Property / Unit', render: r => (
      <div>
        <p className="text-sm text-ink">{r.property || '—'}</p>
        {r.unitNumber && <p className="text-xs text-ink-secondary">Unit {r.unitNumber}</p>}
      </div>
    )},
    { key: 'rentAmount', label: 'Rent', render: r => (
      <div>
        <p className="font-semibold text-ink">{fmt(r.rentAmount)}</p>
        <p className="text-xs text-ink-secondary">{r.paymentMethod || 'EFT'}</p>
      </div>
    )},
    { key: 'leaseEnd', label: 'Lease Expiry', render: r => {
      const info = leaseInfo(r)
      return (
        <div>
          <p className="text-sm text-ink">{r.leaseEnd || '—'}</p>
          {info && <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${info.color}`}>{info.label}</span>}
        </div>
      )
    }},
    { key: 'status', label: 'Status', render: r => (
      <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${STATUS_COLORS[r.status] ?? 'bg-gray-100 text-gray-500'}`}>{r.status}</span>
    )},
    { key: 'actions', label: '', sortable: false, render: r => (
      <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
        <button onClick={() => setViewing(r)} title="View" className="rounded p-1.5 text-ink-secondary hover:bg-surface-2"><Eye size={14} /></button>
        <button onClick={() => openEdit(r)} title="Edit" className="rounded p-1.5 text-primary hover:bg-primary-light"><Pencil size={14} /></button>
        <button onClick={() => handleDownloadPDF(r)} title="Download PDF" disabled={pdfing === r.id}
          className="rounded p-1.5 text-ink-secondary hover:bg-surface-2 disabled:opacity-40">
          {pdfing === r.id ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
        </button>
        <button onClick={() => { if (!window.confirm('Delete this tenant? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'tenants', r.id)) }}
          title="Delete" className="rounded p-1.5 text-red-400 hover:bg-red-50"><Trash2 size={14} /></button>
      </div>
    )},
  ]

  return (
    <div className="space-y-5">
      <PageHead title="Tenants" subtitle="Lease holders, escalation & documents"
        action={<AddButton onClick={() => { setForm(TENANT_BLANK); setDocFile(null); setOpen(true) }}>Add Tenant</AddButton>} />

      {/* Stats */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
        <StatCard label="Active Tenants"  value={active}      icon="👥" color="blue" />
        <StatCard label="On Notice"       value={onNotice}    icon="⚠️" color="orange" trendTone={onNotice ? 'down' : 'up'} />
        <StatCard label="Vacated"         value={vacated}     icon="🚪" trendTone="flat" />
        <StatCard label="Expiring Soon"   value={expiringSoon} icon="📅" color="orange" trendTone={expiringSoon ? 'down' : 'up'} />
        <StatCard label="Monthly Rent Roll" value={fmt(totalRent)} icon="💰" color="purple" />
      </div>

      <DataTable columns={cols} data={tenants} emptyMessage="No tenants yet." onRowClick={setViewing} />

      {/* Add modal */}
      <Modal open={open} onClose={() => setOpen(false)} title="New Tenant" size="xl">
        <TenantFormFields f={form} setF={setForm} properties={properties} docFile={docFile} setDocFile={setDocFile} />
        <button onClick={save} disabled={saving} className="mt-5 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">
          {saving ? 'Saving…' : 'Save Tenant'}
        </button>
      </Modal>

      {/* Edit modal */}
      <Modal open={!!editing} onClose={() => setEditing(null)} title="Edit Tenant" size="xl">
        <TenantFormFields f={editForm} setF={setEditForm} properties={properties} docFile={docFile} setDocFile={setDocFile} />
        <button onClick={saveEdit} disabled={saving} className="mt-5 w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">
          {saving ? 'Saving…' : 'Save Changes'}
        </button>
      </Modal>

      {/* View modal */}
      <Modal open={!!viewing} onClose={() => setViewing(null)} title="Tenant Profile" size="lg">
        {viewing && (() => {
          const info = leaseInfo(viewing)
          const leaseStart = viewing.leaseStart ? new Date(viewing.leaseStart) : null
          const leaseEnd   = viewing.leaseEnd   ? new Date(viewing.leaseEnd)   : null
          const leaseDuration = leaseStart && leaseEnd ? Math.floor((leaseEnd - leaseStart) / 86400000) : 0
          const leaseElapsed  = leaseStart ? Math.floor((new Date() - leaseStart) / 86400000) : 0
          const leasePct = leaseDuration > 0 ? Math.min(Math.max((leaseElapsed / leaseDuration) * 100, 0), 100) : 0

          return (
            <div className="space-y-5 text-sm">
              {/* Identity header */}
              <div className="flex items-start justify-between gap-4 rounded-2xl bg-gradient-to-br from-primary-light/50 to-surface-2 px-5 py-4">
                <div className="flex items-center gap-3">
                  <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-primary text-lg font-bold text-white">
                    {(viewing.firstName || '?').charAt(0)}{(viewing.lastName || '').charAt(0)}
                  </div>
                  <div>
                    <p className="text-base font-bold text-ink">{viewing.firstName} {viewing.lastName}</p>
                    {viewing.idNumber && <p className="text-xs text-ink-secondary">ID: {viewing.idNumber}</p>}
                    <p className="text-xs text-ink-secondary mt-0.5">{viewing.property}{viewing.unitNumber ? ` · Unit ${viewing.unitNumber}` : ''}</p>
                  </div>
                </div>
                <span className={`flex-shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${STATUS_COLORS[viewing.status] ?? 'bg-gray-100 text-gray-500'}`}>{viewing.status}</span>
              </div>

              {/* Lease progress bar */}
              {leaseStart && leaseEnd && (
                <div className="rounded-xl border border-border bg-white px-4 py-3">
                  <div className="mb-2 flex items-center justify-between">
                    <span className="text-xs font-semibold text-ink">Lease Progress</span>
                    {info && <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${info.color}`}>{info.label}</span>}
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-surface-2">
                    <div className={`h-full rounded-full transition-all ${leasePct > 90 ? 'bg-red-500' : leasePct > 70 ? 'bg-amber-500' : 'bg-primary'}`} style={{ width: `${leasePct}%` }} />
                  </div>
                  <div className="mt-1.5 flex justify-between text-[10px] text-ink-secondary">
                    <span>{viewing.leaseStart}</span>
                    <span>{viewing.leaseEnd}</span>
                  </div>
                </div>
              )}

              {/* Detail sections */}
              {[
                { title: 'Contact', fields: [
                  { label: 'Phone', value: viewing.phone },
                  { label: 'Email', value: viewing.email },
                  { label: 'Employment', value: viewing.employmentStatus },
                  { label: 'Employer', value: viewing.employer },
                  { label: 'Employer Phone', value: viewing.employerPhone },
                ]},
                { title: 'Lease', fields: [
                  { label: 'Lease Type', value: viewing.leaseType },
                  { label: 'Occupants', value: viewing.occupants },
                  { label: 'Parking Bay', value: viewing.parkingBay },
                  { label: 'Pets', value: viewing.petsAllowed },
                ]},
                { title: 'Financial', fields: [
                  { label: 'Monthly Rent', value: fmt(viewing.rentAmount) },
                  { label: 'Deposit Paid', value: viewing.depositPaid ? fmt(viewing.depositPaid) : null },
                  { label: 'Payment Method', value: viewing.paymentMethod },
                  { label: 'Escalation', value: viewing.escalationRate ? `${viewing.escalationRate}% · Month ${viewing.escalationMonth || '—'}` : null },
                ]},
                { title: 'Emergency Contact', fields: [
                  { label: 'Name', value: viewing.emergencyName },
                  { label: 'Relationship', value: viewing.emergencyRelation },
                  { label: 'Phone', value: viewing.emergencyPhone },
                ]},
              ].map(section => {
                const visible = section.fields.filter(f => f.value)
                if (!visible.length) return null
                return (
                  <div key={section.title}>
                    <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-primary">{section.title}</p>
                    <div className="grid grid-cols-2 gap-2">
                      {visible.map(({ label, value }) => (
                        <div key={label} className="rounded-xl bg-surface-2 px-3 py-2.5">
                          <p className="text-[10px] font-semibold uppercase tracking-wide text-ink-secondary">{label}</p>
                          <p className="mt-0.5 text-sm font-medium text-ink">{value}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )
              })}

              {viewing.currentAddress && (
                <div>
                  <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-primary">Previous Address</p>
                  <p className="rounded-xl bg-surface-2 px-3 py-2.5 text-sm text-ink">{viewing.currentAddress}</p>
                </div>
              )}

              {viewing.notes && (
                <div>
                  <p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-primary">Notes</p>
                  <p className="rounded-xl bg-surface-2 px-3 py-2.5 text-sm leading-relaxed text-ink">{viewing.notes}</p>
                </div>
              )}

              {/* Actions */}
              <div className="grid grid-cols-2 gap-3 pt-1">
                <button onClick={() => handleDownloadPDF(viewing)} disabled={pdfing === viewing.id}
                  className="flex items-center justify-center gap-2 rounded-xl border border-border py-2.5 text-sm font-semibold text-ink hover:bg-surface-2 disabled:opacity-50 transition">
                  {pdfing === viewing.id ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
                  Download PDF
                </button>
                <button onClick={() => sendSMS(viewing)} disabled={sending === viewing.id}
                  className="flex items-center justify-center gap-2 rounded-xl border border-border py-2.5 text-sm font-semibold text-ink hover:bg-surface-2 disabled:opacity-50 transition">
                  {sending === viewing.id ? <Loader2 size={14} className="animate-spin" /> : <MessageSquare size={14} />}
                  Send SMS
                </button>
                <button onClick={() => { setViewing(null); openEdit(viewing) }}
                  className="col-span-2 rounded-xl bg-primary py-2.5 text-sm font-semibold text-white hover:bg-[#4e7d6d] transition">
                  Edit Tenant
                </button>
              </div>

              {viewing.documentUrl && (
                <a href={viewing.documentUrl} target="_blank" rel="noreferrer"
                  className="flex items-center justify-center gap-1.5 rounded-xl border border-primary-light py-2.5 text-xs font-semibold text-primary hover:bg-primary-light transition">
                  <FileText size={13} /> View Uploaded Document
                </a>
              )}
            </div>
          )
        })()}
      </Modal>
    </div>
  )
}

// ── Rent Roll ─────────────────────────────────────────────────────────────────
function RentRoll() {
  const { user } = useAuth()
  const uid = user?.uid
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const rentRoll = useCollection(uid ? `users/${uid}/rentRoll` : null)

  const now = new Date()
  const defaultMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const [month, setMonth] = useState(defaultMonth)
  const [payingId, setPayingId] = useState(null)
  const [payModal, setPayModal] = useState(null)
  const [payDate, setPayDate] = useState(new Date().toISOString().slice(0, 10))
  const [applying, setApplying] = useState(false)

  // Entries for selected month
  const monthEntries = useMemo(() => rentRoll.filter(r => r.month === month), [rentRoll, month])

  // For tenants not yet in this month's roll, derive a row
  const rows = useMemo(() => {
    const activeTenants = tenants.filter(t => t.status === 'Active')
    return activeTenants.map(t => {
      const entry = monthEntries.find(e => e.tenantId === t.id)
      const rentAmt = Number(t.rentAmount ?? 0)
      // Arrears aging
      const today = new Date()
      const monthStart = new Date(month + '-01')
      const diffDays = Math.floor((today - monthStart) / 86400000)
      let aging = ''
      if (entry?.status !== 'Paid') {
        if (diffDays >= 90) aging = '90+ days'
        else if (diffDays >= 60) aging = '60 days'
        else if (diffDays >= 30) aging = '30 days'
        else if (diffDays > 0) aging = `${diffDays} days`
      }
      // Escalation detection
      const escMonth = Number(t.escalationMonth)
      const escRate = Number(t.escalationRate ?? 10)
      const currentMonth = now.getMonth() + 1
      const isEscalationMonth = escMonth && escMonth === currentMonth
      return {
        id: entry?.id,
        tenantId: t.id,
        name: `${t.firstName} ${t.lastName}`,
        property: t.property,
        unit: t.unitNumber,
        rentAmount: rentAmt,
        status: entry?.status ?? 'Pending',
        paidDate: entry?.paidDate ?? '',
        aging,
        isEscalationMonth,
        escRate,
        escalationRate: t.escalationRate,
      }
    })
  }, [tenants, monthEntries, month])

  const paid = rows.filter(r => r.status === 'Paid').length
  const arrears = rows.filter(r => r.status === 'Arrears').length
  const totalExpected = rows.reduce((s, r) => s + r.rentAmount, 0)
  const totalCollected = rows.filter(r => r.status === 'Paid').reduce((s, r) => s + r.rentAmount, 0)

  async function recordPayment(row) {
    if (!uid) return
    setPayingId(row.tenantId)
    if (row.id) {
      await updateDoc(doc(db, 'users', uid, 'rentRoll', row.id), { status: 'Paid', paidDate: payDate })
    } else {
      await addDoc(collection(db, 'users', uid, 'rentRoll'), {
        tenantId: row.tenantId, tenantName: row.name, property: row.property,
        unit: row.unit, rentAmount: row.rentAmount, month, status: 'Paid', paidDate: payDate,
        createdAt: serverTimestamp(),
      })
    }
    setPayingId(null)
    setPayModal(null)
  }

  async function markArrears(row) {
    if (!uid) return
    if (row.id) {
      await updateDoc(doc(db, 'users', uid, 'rentRoll', row.id), { status: 'Arrears' })
    } else {
      await addDoc(collection(db, 'users', uid, 'rentRoll'), {
        tenantId: row.tenantId, tenantName: row.name, property: row.property,
        unit: row.unit, rentAmount: row.rentAmount, month, status: 'Arrears',
        createdAt: serverTimestamp(),
      })
    }
  }

  async function applyEscalation(row) {
    if (!uid || !row.tenantId) return
    setApplying(row.tenantId)
    const newRent = Math.round(row.rentAmount * (1 + row.escRate / 100))
    await updateDoc(doc(db, 'users', uid, 'tenants', row.tenantId), { rentAmount: String(newRent) })
    setApplying(null)
  }

  const agingColor = a => {
    if (a.includes('90')) return 'text-red-600 font-bold'
    if (a.includes('60')) return 'text-orange-500 font-semibold'
    if (a.includes('30')) return 'text-amber-500'
    return 'text-ink-secondary'
  }

  const statusBadge = s => ({
    Paid: 'bg-green-100 text-green-700',
    Arrears: 'bg-red-100 text-red-600',
    Pending: 'bg-gray-100 text-gray-500',
  }[s] ?? 'bg-gray-100 text-gray-500')

  return (
    <div className="space-y-4">
      <PageHead title="Rent Roll" subtitle="Daily view — who's paid, who's late"
        action={
          <div className="flex items-center gap-2">
            <input type="month" value={month} onChange={e => setMonth(e.target.value)}
              className="rounded-xl border border-border px-3 py-2 text-sm outline-none focus:border-primary" />
          </div>
        }
      />

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Expected" value={fmt(totalExpected)} icon="📋" trendTone="flat" />
        <StatCard label="Collected" value={fmt(totalCollected)} icon="✅" color="blue" trendTone="up" />
        <StatCard label="Outstanding" value={fmt(totalExpected - totalCollected)} icon="⏳" color="orange" trendTone={totalCollected < totalExpected ? 'down' : 'up'} />
        <StatCard label="In Arrears" value={arrears} icon="🚨" color="orange" trend={`${paid} paid`} trendTone={arrears ? 'down' : 'up'} />
      </div>

      {/* Rent roll table */}
      <div className="overflow-hidden rounded-card border border-border bg-white shadow-card">
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-surface-2 text-xs font-semibold text-ink-secondary">
              <tr>
                {['Tenant', 'Property', 'Unit', 'Rent', 'Status', 'Arrears Age', 'Actions'].map(h => (
                  <th key={h} className="px-4 py-3 text-left">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {rows.length === 0 && (
                <tr><td colSpan={7} className="px-4 py-8 text-center text-ink-secondary text-sm">No active tenants for this month.</td></tr>
              )}
              {rows.map(row => (
                <tr key={row.tenantId} className="hover:bg-surface-2/50 transition">
                  <td className="px-4 py-3 font-medium text-ink">
                    {row.name}
                    {row.isEscalationMonth && (
                      <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-700">
                        <TrendingUp size={10} /> Escalation Due
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-ink-secondary">{row.property}</td>
                  <td className="px-4 py-3 text-ink-secondary">{row.unit}</td>
                  <td className="px-4 py-3 font-semibold text-ink">{fmt(row.rentAmount)}</td>
                  <td className="px-4 py-3">
                    <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${statusBadge(row.status)}`}>{row.status}</span>
                  </td>
                  <td className={`px-4 py-3 text-xs ${row.aging ? agingColor(row.aging) : 'text-ink-secondary'}`}>
                    {row.aging || (row.status === 'Paid' ? '—' : 'Current')}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-1 flex-wrap">
                      {row.status !== 'Paid' && (
                        <>
                          <button onClick={() => { setPayModal(row); setPayDate(new Date().toISOString().slice(0,10)) }}
                            className="rounded px-2 py-1 text-xs font-semibold text-green-700 bg-green-50 hover:bg-green-100">
                            {payingId === row.tenantId ? <Loader2 size={12} className="animate-spin" /> : 'Mark Paid'}
                          </button>
                          <button onClick={() => markArrears(row)}
                            className="rounded px-2 py-1 text-xs font-semibold text-red-600 bg-red-50 hover:bg-red-100">
                            Arrears
                          </button>
                        </>
                      )}
                      {row.isEscalationMonth && row.status === 'Paid' && (
                        <button onClick={() => applyEscalation(row)}
                          className="rounded px-2 py-1 text-xs font-semibold text-amber-700 bg-amber-50 hover:bg-amber-100">
                          {applying === row.tenantId ? <Loader2 size={12} className="animate-spin" /> : `Apply ${row.escRate}% Escalation`}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pay modal */}
      <Modal open={!!payModal} onClose={() => setPayModal(null)} title="Record Payment">
        {payModal && (
          <div className="space-y-4">
            <p className="text-sm text-ink">Recording payment for <strong>{payModal.name}</strong> — {fmt(payModal.rentAmount)}</p>
            <Field label="Payment Date" type="date" value={payDate} onChange={e => setPayDate(e.target.value)} />
            <button onClick={() => recordPayment(payModal)} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Confirm Payment</button>
          </div>
        )}
      </Modal>
    </div>
  )
}


// ── Owner Statements ───────────────────────────────────────────────────────────
function OwnerStatements() {
  const { user, profile } = useAuth()
  const uid = user?.uid
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const statements = useCollection(uid ? `users/${uid}/ownerStatements` : null)
  const [form, setForm] = useState({
    propertyId: '', owner: '', month: new Date().toISOString().slice(0,7),
    rentCollected: '', commission: '8', managementFee: '', expenses: '',
  })
  const [generating, setGenerating] = useState(false)

  const rentCollected = Number(form.rentCollected || 0)
  const commission = Number(form.commission || 0)
  const managementFee = Number(form.managementFee || 0)
  const expenses = Number(form.expenses || 0)
  const commissionAmt = rentCollected * commission / 100
  const netPayout = rentCollected - commissionAmt - managementFee - expenses

  async function generate() {
    if (!uid || !form.propertyId || !form.rentCollected) return
    setGenerating(true)
    const property = properties.find(p => p.id === form.propertyId)
    const data = {
      property: property?.name ?? form.propertyId,
      owner: form.owner || property?.owner || 'Owner',
      month: form.month,
      rentCollected, commission, managementFee, expenses, netPayout,
      businessName: profile?.businessName || profile?.name || 'Tlhiso Property',
      generatedAt: new Date().toLocaleDateString('en-ZA'),
    }
    await addDoc(collection(db, 'users', uid, 'ownerStatements'), { ...data, createdAt: serverTimestamp() })
    await downloadStatementPDF(data)
    setGenerating(false)
  }

  const cols = [
    { key: 'property', label: 'Property' },
    { key: 'owner', label: 'Owner' },
    { key: 'month', label: 'Month' },
    { key: 'rentCollected', label: 'Rent', render: r => fmt(r.rentCollected) },
    { key: 'netPayout', label: 'Net Payout', render: r => <span className="font-semibold text-primary">{fmt(r.netPayout)}</span> },
    { key: 'actions', label: '', sortable: false, render: r => (
      <button onClick={e => { e.stopPropagation(); downloadStatementPDF({ ...r, businessName: profile?.businessName || profile?.name || 'Tlhiso Property', generatedAt: new Date().toLocaleDateString('en-ZA') }) }}
        className="flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold text-primary hover:bg-primary-light">
        <Download size={12} /> PDF
      </button>
    )},
  ]

  return (
    <div className="space-y-6">
      <PageHead title="Owner Statements" subtitle="Generate rent statements & payout summaries for property owners" />

      <div className="rounded-card border border-border bg-white shadow-card p-5">
        <h3 className="text-sm font-bold text-ink mb-4">Generate New Statement</h3>
        <div className="grid grid-cols-2 gap-4">
          <Field label="Property *" select value={form.propertyId} onChange={e => setForm(f=>({...f,propertyId:e.target.value}))}>
            <option value="">Select property…</option>
            {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
          </Field>
          <Field label="Owner Name" value={form.owner} onChange={e => setForm(f=>({...f,owner:e.target.value}))} placeholder="Auto-filled from property" />
          <Field label="Statement Month" type="month" value={form.month} onChange={e => setForm(f=>({...f,month:e.target.value}))} />
          <Field label="Rent Collected (R) *" type="number" value={form.rentCollected} onChange={e => setForm(f=>({...f,rentCollected:e.target.value}))} />
          <Field label="Commission (%)" type="number" value={form.commission} onChange={e => setForm(f=>({...f,commission:e.target.value}))} />
          <Field label="Management Fee (R)" type="number" value={form.managementFee} onChange={e => setForm(f=>({...f,managementFee:e.target.value}))} />
          <div className="col-span-2">
            <Field label="Expenses / Maintenance (R)" type="number" value={form.expenses} onChange={e => setForm(f=>({...f,expenses:e.target.value}))} />
          </div>
        </div>

        {form.rentCollected && (
          <div className="mt-4 rounded-xl bg-surface-2 p-4 space-y-2 text-sm">
            <div className="flex justify-between"><span className="text-ink-secondary">Rent Collected</span><span className="font-semibold">{fmt(rentCollected)}</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Commission ({commission}%)</span><span className="text-red-500">({fmt(commissionAmt)})</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Management Fee</span><span className="text-red-500">({fmt(managementFee)})</span></div>
            <div className="flex justify-between"><span className="text-ink-secondary">Expenses</span><span className="text-red-500">({fmt(expenses)})</span></div>
            <div className="flex justify-between border-t border-border pt-2"><span className="font-bold text-ink">Net Payout to Owner</span><span className="font-bold text-primary text-base">{fmt(netPayout)}</span></div>
          </div>
        )}

        <button onClick={generate} disabled={generating || !form.propertyId || !form.rentCollected}
          className="mt-4 flex items-center gap-2 rounded-xl bg-primary px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">
          {generating ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
          Generate & Download PDF
        </button>
      </div>

      <div>
        <h3 className="text-sm font-bold text-ink mb-3">Statement History</h3>
        <DataTable columns={cols} data={statements} emptyMessage="No statements generated yet." />
      </div>
    </div>
  )
}


// ── Maintenance ───────────────────────────────────────────────────────────────
function Maintenance() {
  const { user } = useAuth()
  const uid = user?.uid
  const logs = useCollection(uid ? `users/${uid}/maintenance` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ property: '', unit: '', description: '', priority: 'Medium', contractor: '', status: 'Open' })

  async function save() {
    if (!uid) return
    await addDoc(collection(db, 'users', uid, 'maintenance'), { ...form, createdAt: serverTimestamp() })
    setOpen(false)
    setForm({ property: '', unit: '', description: '', priority: 'Medium', contractor: '', status: 'Open' })
  }

  const priorityColor = p => ({ High: 'bg-red-100 text-red-700', Medium: 'bg-amber-100 text-amber-700', Low: 'bg-green-100 text-green-700' }[p] ?? '')

  const cols = [
    { key: 'property', label: 'Property' },
    { key: 'unit', label: 'Unit' },
    { key: 'description', label: 'Description' },
    { key: 'priority', label: 'Priority', render: r => <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${priorityColor(r.priority)}`}>{r.priority}</span> },
    { key: 'contractor', label: 'Contractor' },
    { key: 'status', label: 'Status' },
    { key: 'actions', label: '', sortable: false, render: r => (
      <button onClick={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'maintenance', r.id), { status: 'Resolved' }) }}
        className="rounded px-2 py-1 text-xs font-semibold text-green-700 hover:bg-green-50">Resolve</button>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Maintenance" subtitle="Track repairs & contractor jobs"
        action={<AddButton onClick={() => setOpen(true)}>Log Request</AddButton>} />
      <DataTable columns={cols} data={logs} emptyMessage="No maintenance requests." />
      <Modal open={open} onClose={() => setOpen(false)} title="New Maintenance Request">
        <div className="space-y-4">
          <Field label="Property" value={form.property} onChange={e => setForm(f=>({...f,property:e.target.value}))} />
          <Field label="Unit" value={form.unit} onChange={e => setForm(f=>({...f,unit:e.target.value}))} />
          <Field label="Description" textarea value={form.description} onChange={e => setForm(f=>({...f,description:e.target.value}))} />
          <Field label="Priority" select value={form.priority} onChange={e => setForm(f=>({...f,priority:e.target.value}))}>
            {['High','Medium','Low'].map(p=><option key={p}>{p}</option>)}
          </Field>
          <Field label="Assigned Contractor" value={form.contractor} onChange={e => setForm(f=>({...f,contractor:e.target.value}))} />
          <button onClick={save} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white">Save Request</button>
        </div>
      </Modal>
    </div>
  )
}



// ── Appointments (Property) ───────────────────────────────────────────────────
const PROP_APPT_STATUS = ['Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'No-show']

function PropertyAppointments() {
  const { user } = useAuth()
  const uid = user?.uid
  const appointments = useCollection(uid ? `users/${uid}/appointments` : null)
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ tenantId: '', date: new Date().toISOString().slice(0, 10), time: '', purpose: '', status: 'Scheduled', notes: '' })
  const [saving, setSaving] = useState(false)
  const [sendingId, setSendingId] = useState(null)

  async function save() {
    if (!uid || !form.date || !form.time) { alert('Date and time are required.'); return }
    setSaving(true)
    try {
      const tenant = tenants.find(t => t.id === form.tenantId)
      await addDoc(collection(db, 'users', uid, 'appointments'), {
        ...form,
        customer: tenant ? `${tenant.firstName} ${tenant.lastName}` : '',
        customerPhone: tenant?.phone ?? '',
        createdAt: serverTimestamp(),
      })
      setForm({ tenantId: '', date: new Date().toISOString().slice(0, 10), time: '', purpose: '', status: 'Scheduled', notes: '' })
      setOpen(false)
    } finally { setSaving(false) }
  }

  async function sendReminder(appt) {
    if (!appt.customerPhone) { alert('No phone number on file for this tenant.'); return }
    setSendingId(appt.id)
    try {
      const fn = httpsCallable(functions, 'sendSMS')
      const msg = `Reminder: ${appt.customer}, you have a property appointment on ${appt.date} at ${appt.time}. Reply to reschedule.`
      await fn({ to: appt.customerPhone, message: msg })
      await updateDoc(doc(db, 'users', uid, 'appointments', appt.id), { reminderSent: true })
      await addDoc(collection(db, 'users', uid, 'messages'), { to: appt.customerPhone, type: 'sms', body: msg, module: 'appointment-reminder', status: 'sent', sentAt: serverTimestamp() })
    } catch { alert('Reminder failed — check BulkSMS credentials.') } finally { setSendingId(null) }
  }

  const badge = s => ({ Scheduled: 'bg-blue-50 text-blue-600', Confirmed: 'bg-primary-light text-primary', Completed: 'bg-green-50 text-green-600', Cancelled: 'bg-red-50 text-red-500', 'No-show': 'bg-orange-50 text-orange-500' }[s] || 'bg-surface-2 text-ink-secondary')

  const cols = [
    { key: 'date', label: 'Date' },
    { key: 'time', label: 'Time' },
    { key: 'customer', label: 'Tenant' },
    { key: 'purpose', label: 'Purpose' },
    { key: 'status', label: 'Status', render: r => (
      <select value={r.status} onClick={e => e.stopPropagation()} onChange={e => { e.stopPropagation(); updateDoc(doc(db, 'users', uid, 'appointments', r.id), { status: e.target.value }) }}
        className={`rounded-full border-0 px-2 py-1 text-[11px] font-semibold ${badge(r.status)}`}>
        {PROP_APPT_STATUS.map(s => <option key={s}>{s}</option>)}
      </select>
    )},
    { key: 'actions', label: '', sortable: false, render: r => (
      <div className="flex items-center gap-1" onClick={e => e.stopPropagation()}>
        <button onClick={() => sendReminder(r)} disabled={sendingId === r.id} title="Send SMS reminder" className="rounded p-1 text-primary hover:bg-primary-light disabled:opacity-50">
          {sendingId === r.id ? <Loader2 size={14} className="animate-spin" /> : <Bell size={14} />}
        </button>
        <button onClick={() => { if (!window.confirm('Delete this appointment? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'appointments', r.id)) }}
          className="rounded p-1 text-red-400 hover:bg-red-50"><Trash2 size={14} /></button>
      </div>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Appointments" subtitle="Schedule inspections, viewings & meetings"
        action={<AddButton onClick={() => setOpen(true)}>Book Appointment</AddButton>} />
      <DataTable columns={cols} data={appointments} emptyMessage="No appointments yet." />
      <Modal open={open} onClose={() => setOpen(false)} title="Book Appointment">
        <div className="space-y-4">
          <Field label="Tenant (optional)" select value={form.tenantId} onChange={e => setForm(f => ({ ...f, tenantId: e.target.value }))}>
            <option value="">Select tenant…</option>
            {tenants.map(t => <option key={t.id} value={t.id}>{t.firstName} {t.lastName} — {t.property}</option>)}
          </Field>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Date *" type="date" value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))} />
            <Field label="Time *" type="time" value={form.time} onChange={e => setForm(f => ({ ...f, time: e.target.value }))} />
          </div>
          <Field label="Purpose" value={form.purpose} onChange={e => setForm(f => ({ ...f, purpose: e.target.value }))} placeholder="e.g. Inspection, Viewing, Signing" />
          <Field label="Status" select value={form.status} onChange={e => setForm(f => ({ ...f, status: e.target.value }))}>
            {PROP_APPT_STATUS.map(s => <option key={s}>{s}</option>)}
          </Field>
          <Field label="Notes" textarea value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))} />
          <button onClick={save} disabled={saving} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save Appointment'}</button>
        </div>
      </Modal>
    </div>
  )
}

// ── Messages ──────────────────────────────────────────────────────────────────
function Messages() {
  const { user } = useAuth()
  const uid = user?.uid
  const messages = useCollection(uid ? `users/${uid}/messages` : null)
  const sorted = useMemo(() => [...messages].sort((a, b) => (b.sentAt?.toMillis?.() ?? 0) - (a.sentAt?.toMillis?.() ?? 0)), [messages])
  const counts = useMemo(() => { const c = { sms: 0, email: 0, whatsapp: 0 }; messages.forEach(m => { if (m.type in c) c[m.type]++ }); return c }, [messages])
  const channelBadge = t => ({ sms: 'bg-blue-100 text-blue-600', email: 'bg-emerald-100 text-emerald-700', whatsapp: 'bg-green-100 text-green-600' }[t] ?? 'bg-gray-100 text-gray-500')
  const cols = [
    { key: 'type', label: 'Channel', render: r => <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold capitalize ${channelBadge(r.type)}`}>{r.type}</span> },
    { key: 'to', label: 'Recipient' },
    { key: 'body', label: 'Message', render: r => <span className="line-clamp-2 max-w-xs text-sm text-ink-secondary">{r.body}</span> },
    { key: 'module', label: 'Source', render: r => <span className="capitalize text-xs text-ink-secondary">{(r.module || '—').replace(/-/g, ' ')}</span> },
    { key: 'sentAt', label: 'Sent', render: r => <span className="text-xs text-ink-secondary">{r.sentAt?.toDate?.()?.toLocaleDateString('en-ZA') ?? '—'}</span> },
  ]
  return (
    <div className="space-y-4">
      <PageHead title="Messages" subtitle="Log of all messages sent from your account" />
      <div className="grid grid-cols-3 gap-4">
        {[{ label: 'SMS Sent', val: counts.sms, color: 'text-blue-600' }, { label: 'Emails Sent', val: counts.email, color: 'text-emerald-600' }, { label: 'WhatsApp Sent', val: counts.whatsapp, color: 'text-green-600' }].map(s => (
          <div key={s.label} className="rounded-card border border-border bg-white p-4 shadow-card text-center">
            <p className={`text-2xl font-extrabold ${s.color}`}>{s.val}</p>
            <p className="mt-1 text-xs font-semibold text-ink-secondary">{s.label}</p>
          </div>
        ))}
      </div>
      <DataTable columns={cols} data={sorted} emptyMessage="No messages sent yet." />
    </div>
  )
}

// ── Documents ─────────────────────────────────────────────────────────────────
function Documents() {
  const { user } = useAuth()
  const uid = user?.uid
  const docs = useCollection(uid ? `users/${uid}/documents` : null)
  const properties = useCollection(uid ? `users/${uid}/properties` : null)
  const tenants = useCollection(uid ? `users/${uid}/tenants` : null)
  const [open, setOpen] = useState(false)
  const [file, setFile] = useState(null)
  const [form, setForm] = useState({ name: '', category: 'Lease Agreement', propertyId: '', tenantId: '', notes: '' })
  const [uploading, setUploading] = useState(false)

  async function save() {
    if (!uid || !form.name || !file) { alert('Document name and file are required.'); return }
    setUploading(true)
    try {
      const storageRef = ref(storage, `users/${uid}/documents/${Date.now()}_${file.name}`)
      await uploadBytes(storageRef, file)
      const url = await getDownloadURL(storageRef)
      const property = properties.find(p => p.id === form.propertyId)
      const tenant = tenants.find(t => t.id === form.tenantId)
      await addDoc(collection(db, 'users', uid, 'documents'), {
        ...form,
        fileUrl: url,
        fileName: file.name,
        property: property?.name ?? '',
        tenant: tenant ? `${tenant.firstName} ${tenant.lastName}` : '',
        createdAt: serverTimestamp(),
      })
      setOpen(false); setFile(null)
      setForm({ name: '', category: 'Lease Agreement', propertyId: '', tenantId: '', notes: '' })
    } finally { setUploading(false) }
  }

  const cols = [
    { key: 'name', label: 'Document Name' },
    { key: 'category', label: 'Category' },
    { key: 'property', label: 'Property' },
    { key: 'tenant', label: 'Tenant' },
    { key: 'actions', label: '', sortable: false, render: r => (
      <div className="flex items-center gap-2">
        {r.fileUrl && <a href={r.fileUrl} target="_blank" rel="noreferrer" className="rounded px-2 py-1 text-xs font-semibold text-primary hover:bg-primary-light">View</a>}
        <button onClick={e => { e.stopPropagation(); if (!window.confirm('Delete this document? This cannot be undone.')) return; deleteDoc(doc(db, 'users', uid, 'documents', r.id)) }}
          className="rounded p-1 text-red-400 hover:bg-red-50"><Trash2 size={14} /></button>
      </div>
    )},
  ]

  return (
    <div className="space-y-4">
      <PageHead title="Documents" subtitle="Leases, inspection reports & property documents"
        action={<AddButton onClick={() => setOpen(true)}>Upload Document</AddButton>} />
      <DataTable columns={cols} data={docs} emptyMessage="No documents uploaded yet." />
      <Modal open={open} onClose={() => setOpen(false)} title="Upload Document" size="lg">
        <div className="space-y-4">
          <Field label="Document Name *" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} />
          <Field label="Category" select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}>
            {['Lease Agreement', 'Inspection Report', 'Notice', 'Invoice', 'Compliance', 'Other'].map(c => <option key={c}>{c}</option>)}
          </Field>
          <Field label="Property" select value={form.propertyId} onChange={e => setForm(f => ({ ...f, propertyId: e.target.value }))}>
            <option value="">Select property…</option>
            {properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
          </Field>
          <Field label="Tenant (optional)" select value={form.tenantId} onChange={e => setForm(f => ({ ...f, tenantId: e.target.value }))}>
            <option value="">Select tenant…</option>
            {tenants.map(t => <option key={t.id} value={t.id}>{t.firstName} {t.lastName}</option>)}
          </Field>
          <div>
            <span className="mb-1.5 block text-xs font-semibold text-ink-secondary">File *</span>
            <input type="file" onChange={e => setFile(e.target.files?.[0] ?? null)} className="text-sm text-ink-secondary" />
          </div>
          <Field label="Notes" textarea value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))} />
          <button onClick={save} disabled={uploading} className="w-full rounded-xl bg-primary py-2.5 text-sm font-semibold text-white disabled:opacity-60">
            {uploading ? 'Uploading…' : 'Upload Document'}
          </button>
        </div>
      </Modal>
    </div>
  )
}

// ── Settings ──────────────────────────────────────────────────────────────────
function Settings() {
  return <SettingsPage industry="property" />
}

export default function PropertyDashboard() {
  return (
    <DashboardLayout industry="property" pageTitle="Property Management">
      <Routes>
        <Route path="dashboard" element={<Overview />} />
        <Route path="properties" element={<Properties />} />
        <Route path="tenants" element={<Tenants />} />
        <Route path="rent-roll" element={<RentRoll />} />
        <Route path="statements" element={<OwnerStatements />} />
        <Route path="maintenance" element={<Maintenance />} />
        <Route path="appointments" element={<PropertyAppointments />} />
        <Route path="messages" element={<Messages />} />
        <Route path="documents" element={<Documents />} />
        <Route path="campaigns" element={<CampaignsModule industry="property" />} />
        <Route path="profile" element={<ProfilePage industry="property" />} />
        <Route path="settings" element={<Settings />} />
        <Route path="*" element={<div><h2 className="text-base font-bold text-ink mb-3">Coming Soon</h2><p className="text-sm text-ink-secondary">This section is being built.</p></div>} />
      </Routes>
    </DashboardLayout>
  )
}
